from django.db import models

class ProtocolHubzugLiftingHost(models.Model):
    count = models.PositiveIntegerField(default=12)
    
    isSaved = models.BooleanField(default=False)
    isClosed = models.BooleanField(default=False)
    isExported = models.BooleanField(default=False)
    isCorrecturNeeded = models.BooleanField(default=False)
    isPermanentDone = models.BooleanField(default=False)
    isNacharbeitNeeded = models.BooleanField(default=False)

    text_1_1 = models.TextField(null=True, blank=True)
    text_1_1_remark = models.TextField(null=True, blank=True)
    text_1_2 = models.TextField(null=True, blank=True)
    text_1_2_remark = models.TextField(null=True, blank=True)

    oknok_3_6 = models.TextField(null=True, blank=True)
    oknok_3_6_soll = models.TextField(default = "93", null=True, blank=True)
    oknok_3_6_remark = models.TextField(null=True, blank=True)
    oknok_1_7 = models.TextField(null=True, blank=True)
    oknok_1_7_soll = models.TextField(default = "55", null=True, blank=True)
    oknok_1_7_remark = models.TextField(null=True, blank=True)

    check_size_10_2 = models.TextField(null=True, blank=True)
    check_size_10_2_soll = models.TextField(default = "245", null=True, blank=True)
    check_size_10_2_soll_avr = models.TextField(default = "3", null=True, blank=True)
    check_size_10_2_remark = models.TextField(null=True, blank=True)

    
    
    oknok_3_6 = models.TextField(verbose_name="1.1", null=True, blank=True)
    protocolName = models.CharField(max_length=255, default="Maßkontrolle Rahmen")
    drawing = models.TextField(verbose_name="Zeichnung-Nr / Drawing No.", null=True, blank=True)
    rev = models.TextField(verbose_name="Rev", null=True, blank=True)
    order = models.TextField(verbose_name="Auftragsnr. / Order No.", null=True, blank=True)
    order_sag = models.TextField(verbose_name="Auftragsnr.-SAG / Order No.-SAG", null=True, blank=True)
    device = models.TextField(verbose_name="Geräte-Nr. / Device No.", null=True, blank=True)
    hoist = models.TextField(verbose_name="Hubzug-Nr. / Hoist No.", null=True, blank=True)
    company = models.TextField(verbose_name="Firma / Company", null=True, blank=True)
    quantity = models.TextField(verbose_name="Stückzahl / Quantity", null=True, blank=True)
    check_size_1 = models.TextField(verbose_name="Visual inspection of weldings, sampling, welding bend, check size of welding seams / EXC3", null=True, blank=True)
    oknok_size_1 = models.TextField(verbose_name="Tighten screws M12x65-8.8-A2F MA=93Nm", null=True, blank=True)
    check_size_3 = models.TextField(verbose_name="wooden block height between bottom of traverse and top of upper frameand lower frame. Front and Rear. Same heigth for all carriers", null=True, blank=True)
    check_size_4 = models.TextField(verbose_name="4. Durchmesser 2. Anschlussbohrung / Diameter of 2nd connecting hole", null=True, blank=True)
    check_size_4a = models.TextField(verbose_name="4a. Abstand zwischen Gehäuseseiten* / Distance between the frame sides *", null=True, blank=True)
    check_size_5 = models.TextField(verbose_name="5. Horizontaler Abstand zu Lochkreismitte für Lageranbau* / Horizontal distance to centre of drum bearing*", null=True, blank=True)
    check_size_6 = models.TextField(verbose_name="6. Vertikaler Abstand zu Lochkreismitte für Lageranbau* / Vertical distance to centre of drum bearing*", null=True, blank=True)
    check_size_7 = models.TextField(verbose_name="7. Durchmesser der Lagerbohrung* / Diameter of the holes for the bearings*", null=True, blank=True)
    check_size_8 = models.TextField(verbose_name="8. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)
    check_size_9 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)
    check_size_10 = models.TextField(verbose_name="10. Durchmesser der beiden Aufnahmebohrungen der Klinke / Diameter of both holes for the Catch lever", null=True, blank=True)
    position_tolerance_11 = models.TextField(verbose_name="11. Rechtwinkligkeit Trommellagerachse zu beiden Flächen der Seitenscheiben Pos. 1+2 / Right angle drum axle to both sides of the hoist frame Pos. 1 and Pos. 2", null=True, blank=True)
    check_size_1_soll =  models.TextField(default = "1230", null=True, blank=True)
    check_size_1_soll_avr =  models.TextField(default = "1.2", null=True, blank=True)
    oknok_size_1_soll =  models.TextField(default = "245", null=True, blank=True)
    check_size_2_soll_avr =  models.TextField(default = "0.5", null=True, blank=True)
    check_size_3_soll =  models.TextField(default = "23", null=True, blank=True)
    check_size_3_soll_avr =  models.TextField(default = "0.2", null=True, blank=True)
    check_size_4_soll =  models.TextField(default = "23", null=True, blank=True)
    check_size_4_soll_avr =  models.TextField(default = "0.2", null=True, blank=True)
    check_size_4a_soll =  models.TextField(default = "1156", null=True, blank=True)
    check_size_4a_soll_avr =  models.TextField(default = "0.5", null=True, blank=True)
    check_size_5_soll =  models.TextField(default = "300", null=True, blank=True)
    check_size_5_soll_avr =  models.TextField(default = "0.5", null=True, blank=True)
    check_size_6_soll =  models.TextField(default = "204", null=True, blank=True)
    check_size_6_soll_avr =  models.TextField(default = "0.5", null=True, blank=True)
    check_size_7_soll =  models.TextField(default = "150", null=True, blank=True)
    check_size_7_soll_avr =  models.TextField(default = "0.15", null=True, blank=True)
    check_size_8_soll =  models.TextField(default = "115", null=True, blank=True)
    check_size_8_soll_avr =  models.TextField(default = "0.1", null=True, blank=True)
    check_size_9_soll =  models.TextField(default = "150", null=True, blank=True)
    check_size_9_soll_avr =  models.TextField(default = "0.1", null=True, blank=True)
    check_size_10_soll =  models.TextField(default = "35", null=True, blank=True)
    check_size_10_soll_avr =  models.TextField(default = "0.025", null=True, blank=True)
    position_tolerance_11_soll =  models.TextField(default = "0.3", null=True, blank=True)
    position_tolerance_11_soll_avr =  models.TextField(default = "0", null=True, blank=True)
    miscellaneous = models.TextField(verbose_name="Sonstiges / Miscellaneous", blank=True, null=True)
    remark = models.TextField(verbose_name="Bemerkungen / Remarks", blank=True, null=True)
    measure = models.TextField(verbose_name="Messgerät / Measure tools", blank=True, null=True)
    date = models.CharField(verbose_name="Datum / Date", max_length=10, help_text="Format: dd.mm.yyyy", null=True, blank=True)
    inspector = models.CharField(verbose_name="Prüfer / Inspector", max_length=20, null=True, blank=True)
    department = models.TextField(verbose_name="Abteilung / Department", blank=True, null=True)
    last_changer = models.CharField(verbose_name="Last modified by", max_length=100, blank=True, null=True)
    baustelle = models.CharField(verbose_name="Baustelle", max_length=100, blank=True, null=True)

    additional_data = models.JSONField(default=dict, blank=True, null=True)
    
class ProtocolHubzugLaufSeiltrommel(models.Model):
    isSaved = models.BooleanField(default=False)
    isClosed = models.BooleanField(default=False)
    isExported = models.BooleanField(default=False)
    isCorrecturNeeded = models.BooleanField(default=False)

    protocolName  = models.CharField(max_length=255, default="Lauf Seiltrommel")
    drawing = models.TextField(verbose_name="Zeichnung-Nr / Drawing No.", null=True, blank=True)
    rev = models.TextField(verbose_name="Rev", null=True, blank=True)
    order = models.TextField(verbose_name="Auftragsnr. / Order No.", null=True, blank=True)
    order_sag = models.TextField(verbose_name="Auftragsnr.-SAG / Order No.-SAG", null=True, blank=True)
    component = models.TextField(verbose_name="Benennung/Component", null=True, blank=True)
    company = models.TextField(verbose_name="Firma / Company", null=True, blank=True)
    quantity = models.TextField(verbose_name="Stückzahl / Quantity", null=True, blank=True)
    baustelle = models.TextField(verbose_name="Baustelle", null=True, blank=True)
    check_size_1 = models.TextField(verbose_name="1. Horizontaler Abstand der Anschlussbohrungen* / Horizontal distance of connecting holes*", null=True, blank=True)
    check_size_2 = models.TextField(verbose_name="2. Vertikaler Abstand der Anschlussbohrungen / Vertical distance of connecting holes*", null=True, blank=True)
    check_size_3 = models.TextField(verbose_name="3. Durchmesser 1.Anschlussbohrung / Diameter of 1st connecting hole", null=True, blank=True)
    check_size_4 = models.TextField(verbose_name="4. Durchmesser 2. Anschlussbohrung / Diameter of 2nd connecting hole", null=True, blank=True)
    check_size_5 = models.TextField(verbose_name="5. Horizontaler Abstand zu Lochkreismitte für Lageranbau* / Horizontal distance to centre of drum bearing*", null=True, blank=True)
    check_size_6 = models.TextField(verbose_name="6. Vertikaler Abstand zu Lochkreismitte für Lageranbau* / Vertical distance to centre of drum bearing*", null=True, blank=True)
    check_size_7 = models.TextField(verbose_name="7. Durchmesser der Lagerbohrung* / Diameter of the holes for the bearings*", null=True, blank=True)
    check_size_8 = models.TextField(verbose_name="8. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)
    check_size_9 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)
    miscellaneous = models.TextField(verbose_name="Sonstiges / Miscellaneous", blank=True, null=True)
    remark = models.TextField(verbose_name="Bemerkungen / Remarks", blank=True, null=True)
    date = models.CharField(verbose_name="Datum / Date", max_length=10, help_text="Format: dd.mm.yyyy", null=True, blank=True)
    inspector = models.CharField(verbose_name="Prüfer / Inspector", max_length=20, null=True, blank=True)
    department = models.TextField(verbose_name="Abteilung / Department", blank=True, null=True)
    last_changer = models.CharField(verbose_name="Last modified by", max_length=100, blank=True, null=True)

class ProtocolHubzugMassSeiltrommel(models.Model):
    isSaved = models.BooleanField(default=False)
    isClosed = models.BooleanField(default=False)
    isExported = models.BooleanField(default=False)
    isCorrecturNeeded = models.BooleanField(default=False)

    protocolName  = models.CharField(max_length=255, default="Mass Seiltrommel")
    drawing = models.TextField(verbose_name="Zeichnung-Nr / Drawing No.", null=True, blank=True)
    rev = models.TextField(verbose_name="Rev", null=True, blank=True)
    order = models.TextField(verbose_name="Auftragsnr. / Order No.", null=True, blank=True)
    order_sag = models.TextField(verbose_name="Auftragsnr.-SAG / Order No.-SAG", null=True, blank=True)
    device = models.TextField(verbose_name="Device", null=True, blank=True)
    component = models.TextField(verbose_name="Benennung/Component", null=True, blank=True)
    company = models.TextField(verbose_name="Firma / Company", null=True, blank=True)
    quantity = models.TextField(verbose_name="Stückzahl / Quantity", null=True, blank=True)
    baustelle = models.TextField(verbose_name="Baustelle", null=True, blank=True)
    check_size_1 = models.TextField(verbose_name="1. Horizontaler Abstand der Anschlussbohrungen* / Horizontal distance of connecting holes*", null=True, blank=True)
    check_size_2 = models.TextField(verbose_name="2. Vertikaler Abstand der Anschlussbohrungen / Vertical distance of connecting holes*", null=True, blank=True)
    check_size_3 = models.TextField(verbose_name="3. Durchmesser 1.Anschlussbohrung / Diameter of 1st connecting hole", null=True, blank=True)
    check_size_4 = models.TextField(verbose_name="4. Durchmesser 2. Anschlussbohrung / Diameter of 2nd connecting hole", null=True, blank=True)
    check_size_5 = models.TextField(verbose_name="5. Horizontaler Abstand zu Lochkreismitte für Lageranbau* / Horizontal distance to centre of drum bearing*", null=True, blank=True)
    check_size_6 = models.TextField(verbose_name="6. Vertikaler Abstand zu Lochkreismitte für Lageranbau* / Vertical distance to centre of drum bearing*", null=True, blank=True)
    check_size_7 = models.TextField(verbose_name="7. Durchmesser der Lagerbohrung* / Diameter of the holes for the bearings*", null=True, blank=True)
    check_size_8 = models.TextField(verbose_name="8. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)
    check_size_9 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)
    check_size_10 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)
    check_size_11 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)
    check_size_12 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)
    check_size_13 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)    
    miscellaneous = models.TextField(verbose_name="Sonstiges / Miscellaneous", blank=True, null=True)
    remark = models.TextField(verbose_name="Bemerkungen / Remarks", blank=True, null=True)
    date = models.CharField(verbose_name="Datum / Date", max_length=10, help_text="Format: dd.mm.yyyy", null=True, blank=True)
    inspector = models.CharField(verbose_name="Prüfer / Inspector", max_length=20, null=True, blank=True)
    measure = models.CharField(verbose_name="Measure", max_length=20, null=True, blank=True)
    department = models.TextField(verbose_name="Abteilung / Department", blank=True, null=True)
    last_changer = models.CharField(verbose_name="Last modified by", max_length=100, blank=True, null=True)

class ProtocolLaufHubzug(models.Model):
    isSaved = models.BooleanField(default=False)
    isClosed = models.BooleanField(default=False)
    isExported = models.BooleanField(default=False)
    isCorrecturNeeded = models.BooleanField(default=False)
    isNacharbeiterNeeded = models.BooleanField(default=False)
    isPermanentDone = models.BooleanField(default=False)

    protocolName  = models.CharField(max_length=255, default="Laufschein Hubzug")
    drawing = models.TextField(verbose_name="Zeichnung-Nr / Drawing No.", null=True, blank=True)
    rev = models.TextField(verbose_name="Rev", null=True, blank=True)
    order = models.TextField(verbose_name="Auftragsnr. / Order No.", null=True, blank=True)
    order_sag = models.TextField(verbose_name="Auftragsnr.-SAG / Order No.-SAG", null=True, blank=True)
    device = models.TextField(verbose_name="Device", null=True, blank=True)
    component = models.TextField(verbose_name="Benennung/Component", null=True, blank=True)
    company = models.TextField(verbose_name="Firma / Company", null=True, blank=True)
    quantity = models.TextField(verbose_name="Stückzahl / Quantity", null=True, blank=True)
    baustelle = models.TextField(verbose_name="Baustelle", null=True, blank=True)
    hoist = models.TextField(verbose_name="Hoist", null=True, blank=True)
    loadTp = models.TextField(verbose_name="Load Tp", null=True, blank=True)
    check_size_1 = models.TextField(verbose_name="1. Horizontaler Abstand der Anschlussbohrungen* / Horizontal distance of connecting holes*", null=True, blank=True)
    check_size_2 = models.TextField(verbose_name="2. Vertikaler Abstand der Anschlussbohrungen / Vertical distance of connecting holes*", null=True, blank=True)
    check_size_3 = models.TextField(verbose_name="3. Durchmesser 1.Anschlussbohrung / Diameter of 1st connecting hole", null=True, blank=True)
    check_size_4 = models.TextField(verbose_name="4. Durchmesser 2. Anschlussbohrung / Diameter of 2nd connecting hole", null=True, blank=True)
    check_size_4a = models.TextField(verbose_name="4. Durchmesser 2. Anschlussbohrung / Diameter of 2nd connecting hole", null=True, blank=True)
    check_size_5 = models.TextField(verbose_name="5. Horizontaler Abstand zu Lochkreismitte für Lageranbau* / Horizontal distance to centre of drum bearing*", null=True, blank=True)
    check_size_6 = models.TextField(verbose_name="6. Vertikaler Abstand zu Lochkreismitte für Lageranbau* / Vertical distance to centre of drum bearing*", null=True, blank=True)
    check_size_7 = models.TextField(verbose_name="7. Durchmesser der Lagerbohrung* / Diameter of the holes for the bearings*", null=True, blank=True)
    check_size_8 = models.TextField(verbose_name="8. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)
    check_size_9 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)
    check_size_10 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)
    check_size_11 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)
    check_size_12 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)
    check_size_13 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)    
    check_size_14 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)    
    check_size_15 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)    
    check_size_16 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)    
    check_size_17 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)    
    check_size_18 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)    
    check_size_19 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)    
    check_size_20 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)    
    check_size_21 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)    
    check_size_22 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)    
    check_size_23 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)    

    miscellaneous = models.TextField(verbose_name="Sonstiges / Miscellaneous", blank=True, null=True)
    remark = models.TextField(verbose_name="Bemerkungen / Remarks", blank=True, null=True)
    date = models.CharField(verbose_name="Datum / Date", max_length=10, help_text="Format: dd.mm.yyyy", null=True, blank=True)
    inspector = models.CharField(verbose_name="Prüfer / Inspector", max_length=20, null=True, blank=True)
    measure = models.CharField(verbose_name="Measure", max_length=20, null=True, blank=True)
    department = models.TextField(verbose_name="Abteilung / Department", blank=True, null=True)
    last_changer = models.CharField(verbose_name="Last modified by", max_length=100, blank=True, null=True)

class ProtocolEndkontrolle(models.Model):
    isSaved = models.BooleanField(default=False)
    isClosed = models.BooleanField(default=False)
    isExported = models.BooleanField(default=False)
    isCorrecturNeeded = models.BooleanField(default=False)

    protocolName  = models.CharField(max_length=255, default="Endkontrolle")
    drawing = models.TextField(verbose_name="Zeichnung-Nr / Drawing No.", null=True, blank=True)
    rev = models.TextField(verbose_name="Rev", null=True, blank=True)
    order = models.TextField(verbose_name="Auftragsnr. / Order No.", null=True, blank=True)
    order_sag = models.TextField(verbose_name="Auftragsnr.-SAG / Order No.-SAG", null=True, blank=True)
    device = models.TextField(verbose_name="Device", null=True, blank=True)
    component = models.TextField(verbose_name="Benennung/Component", null=True, blank=True)
    company = models.TextField(verbose_name="Firma / Company", null=True, blank=True)
    quantity = models.TextField(verbose_name="Stückzahl / Quantity", null=True, blank=True)
    baustelle = models.TextField(verbose_name="Baustelle", null=True, blank=True)
    hoist = models.TextField(verbose_name="Hoist", null=True, blank=True)
    loadTp = models.TextField(verbose_name="Load Tp", null=True, blank=True)
    unitNO =  models.TextField(verbose_name="UnitNo", null=True, blank=True)
    check_size_1 = models.TextField(verbose_name="1. Horizontaler Abstand der Anschlussbohrungen* / Horizontal distance of connecting holes*", null=True, blank=True)
    check_size_2 = models.TextField(verbose_name="2. Vertikaler Abstand der Anschlussbohrungen / Vertical distance of connecting holes*", null=True, blank=True)
    check_size_3 = models.TextField(verbose_name="3. Durchmesser 1.Anschlussbohrung / Diameter of 1st connecting hole", null=True, blank=True)
    check_size_4 = models.TextField(verbose_name="4. Durchmesser 2. Anschlussbohrung / Diameter of 2nd connecting hole", null=True, blank=True)
    check_size_4a = models.TextField(verbose_name="4. Durchmesser 2. Anschlussbohrung / Diameter of 2nd connecting hole", null=True, blank=True)
    check_size_5 = models.TextField(verbose_name="5. Horizontaler Abstand zu Lochkreismitte für Lageranbau* / Horizontal distance to centre of drum bearing*", null=True, blank=True)
    check_size_5a = models.TextField(verbose_name="5. Horizontaler Abstand zu Lochkreismitte für Lageranbau* / Horizontal distance to centre of drum bearing*", null=True, blank=True)
    check_size_6 = models.TextField(verbose_name="6. Vertikaler Abstand zu Lochkreismitte für Lageranbau* / Vertical distance to centre of drum bearing*", null=True, blank=True)
    check_size_6a = models.TextField(verbose_name="5. Horizontaler Abstand zu Lochkreismitte für Lageranbau* / Horizontal distance to centre of drum bearing*", null=True, blank=True)
    check_size_7 = models.TextField(verbose_name="7. Durchmesser der Lagerbohrung* / Diameter of the holes for the bearings*", null=True, blank=True)
    check_size_8 = models.TextField(verbose_name="8. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)
    check_size_9 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)
    check_size_10 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)
    check_size_11 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)
    check_size_12 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)
    check_size_13 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)    
    check_size_14 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)    
    check_size_15 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)    
    check_size_16 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)    
    check_size_17 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)    
    check_size_18 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)    
    check_size_19 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)    
    check_size_20 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)    
    check_size_21 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)    
    check_size_22 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)    
    check_size_23 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)    

    miscellaneous = models.TextField(verbose_name="Sonstiges / Miscellaneous", blank=True, null=True)
    remark = models.TextField(verbose_name="Bemerkungen / Remarks", blank=True, null=True)
    date = models.CharField(verbose_name="Datum / Date", max_length=10, help_text="Format: dd.mm.yyyy", null=True, blank=True)
    inspector = models.CharField(verbose_name="Prüfer / Inspector", max_length=20, null=True, blank=True)
    measure = models.CharField(verbose_name="Measure", max_length=20, null=True, blank=True)
    department = models.TextField(verbose_name="Abteilung / Department", blank=True, null=True)
    last_changer = models.CharField(verbose_name="Last modified by", max_length=100, blank=True, null=True)

