from django.db import models

class ProtocolHubzugLiftingHost(models.Model):
    count = models.PositiveIntegerField(default=12)
    
    isSaved = models.BooleanField(default=False)
    isClosed = models.BooleanField(default=False)
    isExported = models.BooleanField(default=False)
    isCorrecturNeeded = models.BooleanField(default=False)
    isPermanentDone = models.BooleanField(default=False)
    isNacharbeitNeeded = models.BooleanField(default=False)

    oknok_1_1 = models.TextField(null=True, blank=True)
    oknok_1_1_soll = models.TextField(null=True, blank=True)
    oknok_1_1_remark = models.TextField(null=True, blank=True)
    oknok_1_2 = models.TextField(null=True, blank=True)
    oknok_1_2_soll = models.TextField(null=True, blank=True)
    oknok_1_2_remark = models.TextField(null=True, blank=True)
    oknok_1_3 = models.TextField(null=True, blank=True)
    oknok_1_3_soll = models.TextField(null=True, blank=True)
    oknok_1_3_remark = models.TextField(null=True, blank=True)
    oknok_1_4 = models.TextField(null=True, blank=True)
    oknok_1_4_soll = models.TextField(default = "461", null=True, blank=True)
    oknok_1_4_remark = models.TextField(null=True, blank=True)
    oknok_1_5 = models.TextField(null=True, blank=True)
    oknok_1_5_soll = models.TextField(null=True, blank=True)
    oknok_1_5_remark = models.TextField(null=True, blank=True)
    oknok_1_6 = models.TextField(null=True, blank=True)
    oknok_1_6_soll = models.TextField(null=True, blank=True)
    oknok_1_6_remark = models.TextField(null=True, blank=True)
    oknok_1_7 = models.TextField(null=True, blank=True)
    oknok_1_7_soll = models.TextField(null=True, blank=True)
    oknok_1_7_remark = models.TextField(null=True, blank=True)
    oknok_1_8 = models.TextField(null=True, blank=True)
    oknok_1_8_soll = models.TextField(null=True, blank=True)
    oknok_1_8_remark = models.TextField(null=True, blank=True)
    oknok_1_9 = models.TextField(null=True, blank=True)
    oknok_1_9_soll = models.TextField(null=True, blank=True)
    oknok_1_9_remark = models.TextField(null=True, blank=True)
    oknok_1_10 = models.TextField(null=True, blank=True)
    oknok_1_10_soll = models.TextField(null=True, blank=True)
    oknok_1_10_remark = models.TextField(null=True, blank=True)
    oknok_1_11 = models.TextField(null=True, blank=True)
    oknok_1_11_soll = models.TextField(null=True, blank=True)
    oknok_1_11_remark = models.TextField(null=True, blank=True)
    oknok_1_12 = models.TextField(null=True, blank=True)
    oknok_1_12_soll = models.TextField(null=True, blank=True)
    oknok_1_12_remark = models.TextField(null=True, blank=True)
    oknok_1_13 = models.TextField(null=True, blank=True)
    oknok_1_13_soll = models.TextField(null=True, blank=True)
    oknok_1_13_remark = models.TextField(null=True, blank=True)
    oknok_1_14 = models.TextField(null=True, blank=True)
    oknok_1_14_soll = models.TextField(null=True, blank=True)
    oknok_1_14_remark = models.TextField(null=True, blank=True)
    oknok_1_15 = models.TextField(null=True, blank=True)
    oknok_1_15_soll = models.TextField(null=True, blank=True)
    oknok_1_15_remark = models.TextField(null=True, blank=True)
    oknok_1_16 = models.TextField(null=True, blank=True)
    oknok_1_16_soll = models.TextField(null=True, blank=True)
    oknok_1_16_remark = models.TextField(null=True, blank=True)
    oknok_1_17 = models.TextField(null=True, blank=True)
    oknok_1_17_soll = models.TextField(null=True, blank=True)
    oknok_1_17_remark = models.TextField(null=True, blank=True)
    oknok_1_18 = models.TextField(null=True, blank=True)
    oknok_1_18_soll = models.TextField(null=True, blank=True)
    oknok_1_18_remark = models.TextField(null=True, blank=True)
    oknok_1_19 = models.TextField(null=True, blank=True)
    oknok_1_19_soll = models.TextField(null=True, blank=True)
    oknok_1_19_remark = models.TextField(null=True, blank=True)
    oknok_1_20 = models.TextField(null=True, blank=True)
    oknok_1_20_soll = models.TextField(null=True, blank=True)
    oknok_1_20_remark = models.TextField(null=True, blank=True)
    oknok_1_23 = models.TextField(null=True, blank=True)
    oknok_1_23_soll = models.TextField(null=True, blank=True)
    oknok_1_23_remark = models.TextField(null=True, blank=True)
    oknok_1_24 = models.TextField(null=True, blank=True)
    oknok_1_24_soll = models.TextField(null=True, blank=True)
    oknok_1_24_remark = models.TextField(null=True, blank=True)
    oknok_1_25 = models.TextField(null=True, blank=True)
    oknok_1_25_soll = models.TextField(null=True, blank=True)
    oknok_1_25_remark = models.TextField(null=True, blank=True)
    oknok_1_26 = models.TextField(null=True, blank=True)
    oknok_1_26_soll = models.TextField(null=True, blank=True)
    oknok_1_26_remark = models.TextField(null=True, blank=True)
    oknok_1_27 = models.TextField(null=True, blank=True)
    oknok_1_27_soll = models.TextField(null=True, blank=True)
    oknok_1_27_remark = models.TextField(null=True, blank=True)
    oknok_1_28 = models.TextField(null=True, blank=True)
    oknok_1_28_soll = models.TextField(null=True, blank=True)
    oknok_1_28_remark = models.TextField(null=True, blank=True)
    oknok_1_29 = models.TextField(null=True, blank=True)
    oknok_1_29_soll = models.TextField(null=True, blank=True)
    oknok_1_29_remark = models.TextField(null=True, blank=True)
    oknok_1_30 = models.TextField(null=True, blank=True)
    oknok_1_30_soll = models.TextField(null=True, blank=True)
    oknok_1_30_remark = models.TextField(null=True, blank=True)
    oknok_1_31 = models.TextField(null=True, blank=True)
    oknok_1_31_soll = models.TextField(null=True, blank=True)
    oknok_1_31_remark = models.TextField(null=True, blank=True)
    oknok_1_32 = models.TextField(null=True, blank=True)
    oknok_1_32_soll = models.TextField(null=True, blank=True)
    oknok_1_32_remark = models.TextField(null=True, blank=True)
    oknok_1_33 = models.TextField(null=True, blank=True)
    oknok_1_33_soll = models.TextField(null=True, blank=True)
    oknok_1_33_remark = models.TextField(null=True, blank=True)
    oknok_1_34 = models.TextField(null=True, blank=True)
    oknok_1_34_soll = models.TextField(null=True, blank=True)
    oknok_1_34_remark = models.TextField(null=True, blank=True)
    oknok_1_35 = models.TextField(null=True, blank=True)
    oknok_1_35_soll = models.TextField(null=True, blank=True)
    oknok_1_35_remark = models.TextField(null=True, blank=True)
    oknok_1_36 = models.TextField(null=True, blank=True)
    oknok_1_36_soll = models.TextField(null=True, blank=True)
    oknok_1_36_remark = models.TextField(null=True, blank=True)
    oknok_2_1 = models.TextField(null=True, blank=True)
    oknok_2_1_soll = models.TextField(null=True, blank=True)
    oknok_2_1_remark = models.TextField(null=True, blank=True)
    oknok_2_2 = models.TextField(null=True, blank=True)
    oknok_2_2_soll = models.TextField(null=True, blank=True)
    oknok_2_2_remark = models.TextField(null=True, blank=True)
    oknok_2_3 = models.TextField(null=True, blank=True)
    oknok_2_3_soll = models.TextField(null=True, blank=True)
    oknok_2_3_remark = models.TextField(null=True, blank=True)
    oknok_2_4 = models.TextField(null=True, blank=True)
    oknok_2_4_soll = models.TextField(null=True, blank=True)
    oknok_2_4_remark = models.TextField(null=True, blank=True)
    oknok_2_5 = models.TextField(null=True, blank=True)
    oknok_2_5_soll = models.TextField(null=True, blank=True)
    oknok_2_5_remark = models.TextField(null=True, blank=True)
    oknok_2_6 = models.TextField(null=True, blank=True)
    oknok_2_6_soll = models.TextField(null=True, blank=True)
    oknok_2_6_remark = models.TextField(null=True, blank=True)
    oknok_2_7 = models.TextField(null=True, blank=True)
    oknok_2_7_soll = models.TextField(null=True, blank=True)
    oknok_2_7_remark = models.TextField(null=True, blank=True)
    oknok_2_8 = models.TextField(null=True, blank=True)
    oknok_2_8_soll = models.TextField(null=True, blank=True)
    oknok_2_8_remark = models.TextField(null=True, blank=True)
    oknok_2_9 = models.TextField(null=True, blank=True)
    oknok_2_9_soll = models.TextField(null=True, blank=True)
    oknok_2_9_remark = models.TextField(null=True, blank=True)
    oknok_2_10 = models.TextField(null=True, blank=True)
    oknok_2_10_soll = models.TextField(null=True, blank=True)
    oknok_2_10_remark = models.TextField(null=True, blank=True)
    oknok_2_11 = models.TextField(null=True, blank=True)
    oknok_2_11_soll = models.TextField(null=True, blank=True)
    oknok_2_11_remark = models.TextField(null=True, blank=True)
    oknok_2_12 = models.TextField(null=True, blank=True)
    oknok_2_12_soll = models.TextField(null=True, blank=True)
    oknok_2_12_remark = models.TextField(null=True, blank=True)
    oknok_2_13 = models.TextField(null=True, blank=True)
    oknok_2_13_soll = models.TextField(null=True, blank=True)
    oknok_2_13_remark = models.TextField(null=True, blank=True)
    oknok_2_14 = models.TextField(null=True, blank=True)
    oknok_2_14_soll = models.TextField(null=True, blank=True)
    oknok_2_14_remark = models.TextField(null=True, blank=True)
    oknok_3_1 = models.TextField(null=True, blank=True)
    oknok_3_1_soll = models.TextField(null=True, blank=True)
    oknok_3_1_remark = models.TextField(null=True, blank=True)
    oknok_3_2 = models.TextField(null=True, blank=True)
    oknok_3_2_soll = models.TextField(null=True, blank=True)
    oknok_3_2_remark = models.TextField(null=True, blank=True)
    oknok_3_3 = models.TextField(null=True, blank=True)
    oknok_3_3_soll = models.TextField(null=True, blank=True)
    oknok_3_3_remark = models.TextField(null=True, blank=True)
    oknok_3_4 = models.TextField(null=True, blank=True)
    oknok_3_4_soll = models.TextField(null=True, blank=True)
    oknok_3_4_remark = models.TextField(null=True, blank=True)
    oknok_3_5 = models.TextField(null=True, blank=True)
    oknok_3_5_soll = models.TextField(null=True, blank=True)
    oknok_3_5_remark = models.TextField(null=True, blank=True)
    oknok_3_6 = models.TextField(null=True, blank=True)
    oknok_3_6_soll = models.TextField(null=True, blank=True)
    oknok_3_6_remark = models.TextField(null=True, blank=True)
    oknok_3_8 = models.TextField(null=True, blank=True)
    oknok_3_8_soll = models.TextField(null=True, blank=True)
    oknok_3_8_remark = models.TextField(null=True, blank=True)
    oknok_3_10 = models.TextField(null=True, blank=True)
    oknok_3_10_soll = models.TextField(null=True, blank=True)
    oknok_3_10_remark = models.TextField(null=True, blank=True)
    oknok_3_11 = models.TextField(null=True, blank=True)
    oknok_3_11_soll = models.TextField(null=True, blank=True)
    oknok_3_11_remark = models.TextField(null=True, blank=True)
    oknok_3_12 = models.TextField(null=True, blank=True)
    oknok_3_12_soll = models.TextField(null=True, blank=True)
    oknok_3_12_remark = models.TextField(null=True, blank=True)
    oknok_3_13 = models.TextField(null=True, blank=True)
    oknok_3_13_soll = models.TextField(null=True, blank=True)
    oknok_3_13_remark = models.TextField(null=True, blank=True)
    oknok_3_14 = models.TextField(null=True, blank=True)
    oknok_3_14_soll = models.TextField(null=True, blank=True)
    oknok_3_14_remark = models.TextField(null=True, blank=True)
    oknok_3_15 = models.TextField(null=True, blank=True)
    oknok_3_15_soll = models.TextField(null=True, blank=True)
    oknok_3_15_remark = models.TextField(null=True, blank=True)
    oknok_3_16 = models.TextField(null=True, blank=True)
    oknok_3_16_soll = models.TextField(null=True, blank=True)
    oknok_3_16_remark = models.TextField(null=True, blank=True)
    oknok_3_17 = models.TextField(null=True, blank=True)
    oknok_3_17_soll = models.TextField(null=True, blank=True)
    oknok_3_17_remark = models.TextField(null=True, blank=True)
    oknok_3_18 = models.TextField(null=True, blank=True)
    oknok_3_18_soll = models.TextField(null=True, blank=True)
    oknok_3_18_remark = models.TextField(null=True, blank=True)
    oknok_3_19 = models.TextField(null=True, blank=True)
    oknok_3_19_soll = models.TextField(null=True, blank=True)
    oknok_3_19_remark = models.TextField(null=True, blank=True)
    oknok_3_20 = models.TextField(null=True, blank=True)
    oknok_3_20_soll = models.TextField(null=True, blank=True)
    oknok_3_20_remark = models.TextField(null=True, blank=True)
    oknok_3_21 = models.TextField(null=True, blank=True)
    oknok_3_21_soll = models.TextField(null=True, blank=True)
    oknok_3_21_remark = models.TextField(null=True, blank=True)
    oknok_3_22 = models.TextField(null=True, blank=True)
    oknok_3_22_soll = models.TextField(null=True, blank=True)
    oknok_3_22_remark = models.TextField(null=True, blank=True)
    oknok_3_23 = models.TextField(null=True, blank=True)
    oknok_3_23_soll = models.TextField(null=True, blank=True)
    oknok_3_23_remark = models.TextField(null=True, blank=True)
    oknok_3_24 = models.TextField(null=True, blank=True)
    oknok_3_24_soll = models.TextField(null=True, blank=True)
    oknok_3_24_remark = models.TextField(null=True, blank=True)
    oknok_3_25 = models.TextField(null=True, blank=True)
    oknok_3_25_soll = models.TextField(null=True, blank=True)
    oknok_3_25_remark = models.TextField(null=True, blank=True)
    oknok_3_26 = models.TextField(null=True, blank=True)
    oknok_3_26_soll = models.TextField(null=True, blank=True)
    oknok_3_26_remark = models.TextField(null=True, blank=True)
    oknok_3_27 = models.TextField(null=True, blank=True)
    oknok_3_27_soll = models.TextField(null=True, blank=True)
    oknok_3_27_remark = models.TextField(null=True, blank=True)
    oknok_3_28 = models.TextField(null=True, blank=True)
    oknok_3_28_soll = models.TextField(null=True, blank=True)
    oknok_3_28_remark = models.TextField(null=True, blank=True)
    oknok_3_29 = models.TextField(null=True, blank=True)
    oknok_3_29_soll = models.TextField(null=True, blank=True)
    oknok_3_29_remark = models.TextField(null=True, blank=True)
    oknok_3_30 = models.TextField(null=True, blank=True)
    oknok_3_30_soll = models.TextField(null=True, blank=True)
    oknok_3_30_remark = models.TextField(null=True, blank=True)
    oknok_3_31 = models.TextField(null=True, blank=True)
    oknok_3_31_soll = models.TextField(null=True, blank=True)
    oknok_3_31_remark = models.TextField(null=True, blank=True)
    oknok_3_32 = models.TextField(null=True, blank=True)
    oknok_3_32_soll = models.TextField(null=True, blank=True)
    oknok_3_32_remark = models.TextField(null=True, blank=True)
    oknok_4_1 = models.TextField(null=True, blank=True)
    oknok_4_1_soll = models.TextField(null=True, blank=True)
    oknok_4_1_remark = models.TextField(null=True, blank=True)
    oknok_4_2 = models.TextField(null=True, blank=True)
    oknok_4_2_soll = models.TextField(null=True, blank=True)
    oknok_4_2_remark = models.TextField(null=True, blank=True)
    oknok_4_3 = models.TextField(null=True, blank=True)
    oknok_4_3_soll = models.TextField(null=True, blank=True)
    oknok_4_3_remark = models.TextField(null=True, blank=True)
    oknok_4_4 = models.TextField(null=True, blank=True)
    oknok_4_4_soll = models.TextField(null=True, blank=True)
    oknok_4_4_remark = models.TextField(null=True, blank=True)
    oknok_4_6 = models.TextField(null=True, blank=True)
    oknok_4_6_soll = models.TextField(null=True, blank=True)
    oknok_4_6_remark = models.TextField(null=True, blank=True)
    oknok_4_7 = models.TextField(null=True, blank=True)
    oknok_4_7_soll = models.TextField(null=True, blank=True)
    oknok_4_7_remark = models.TextField(null=True, blank=True)
    oknok_4_8 = models.TextField(null=True, blank=True)
    oknok_4_8_soll = models.TextField(null=True, blank=True)
    oknok_4_8_remark = models.TextField(null=True, blank=True)
    oknok_4_9 = models.TextField(null=True, blank=True)
    oknok_4_9_soll = models.TextField(null=True, blank=True)
    oknok_4_9_remark = models.TextField(null=True, blank=True)
    oknok_4_10 = models.TextField(null=True, blank=True)
    oknok_4_10_soll = models.TextField(null=True, blank=True)
    oknok_4_10_remark = models.TextField(null=True, blank=True)
    oknok_4_11 = models.TextField(null=True, blank=True)
    oknok_4_11_soll = models.TextField(null=True, blank=True)
    oknok_4_11_remark = models.TextField(null=True, blank=True)
    oknok_4_12 = models.TextField(null=True, blank=True)
    oknok_4_12_soll = models.TextField(null=True, blank=True)
    oknok_4_12_remark = models.TextField(null=True, blank=True)
    oknok_4_13 = models.TextField(null=True, blank=True)
    oknok_4_13_soll = models.TextField(null=True, blank=True)
    oknok_4_13_remark = models.TextField(null=True, blank=True)
    oknok_4_14 = models.TextField(null=True, blank=True)
    oknok_4_14_soll = models.TextField(null=True, blank=True)
    oknok_4_14_remark = models.TextField(null=True, blank=True)
    oknok_5_1 = models.TextField(null=True, blank=True)
    oknok_5_1_soll = models.TextField(null=True, blank=True)
    oknok_5_1_remark = models.TextField(null=True, blank=True)
    oknok_5_2 = models.TextField(null=True, blank=True)
    oknok_5_2_soll = models.TextField(null=True, blank=True)
    oknok_5_2_remark = models.TextField(null=True, blank=True)
    oknok_5_3 = models.TextField(null=True, blank=True)
    oknok_5_3_soll = models.TextField(null=True, blank=True)
    oknok_5_3_remark = models.TextField(null=True, blank=True)
    oknok_5_4 = models.TextField(null=True, blank=True)
    oknok_5_4_soll = models.TextField(null=True, blank=True)
    oknok_5_4_remark = models.TextField(null=True, blank=True)
    oknok_5_5 = models.TextField(null=True, blank=True)
    oknok_5_5_soll = models.TextField(null=True, blank=True)
    oknok_5_5_remark = models.TextField(null=True, blank=True)
    oknok_5_6 = models.TextField(null=True, blank=True)
    oknok_5_6_soll = models.TextField(null=True, blank=True)
    oknok_5_6_remark = models.TextField(null=True, blank=True)
    oknok_5_7 = models.TextField(null=True, blank=True)
    oknok_5_7_soll = models.TextField(null=True, blank=True)
    oknok_5_7_remark = models.TextField(null=True, blank=True)
    oknok_5_8 = models.TextField(null=True, blank=True)
    oknok_5_8_soll = models.TextField(null=True, blank=True)
    oknok_5_8_remark = models.TextField(null=True, blank=True)
    oknok_5_9 = models.TextField(null=True, blank=True)
    oknok_5_9_soll = models.TextField(null=True, blank=True)
    oknok_5_9_remark = models.TextField(null=True, blank=True)
    oknok_5_10 = models.TextField(null=True, blank=True)
    oknok_5_10_soll = models.TextField(null=True, blank=True)
    oknok_5_10_remark = models.TextField(null=True, blank=True)
    oknok_5_11 = models.TextField(null=True, blank=True)
    oknok_5_11_soll = models.TextField(null=True, blank=True)
    oknok_5_11_remark = models.TextField(null=True, blank=True)
    oknok_5_12 = models.TextField(null=True, blank=True)
    oknok_5_12_soll = models.TextField(null=True, blank=True)
    oknok_5_12_remark = models.TextField(null=True, blank=True)
    oknok_5_13 = models.TextField(null=True, blank=True)
    oknok_5_13_soll = models.TextField(null=True, blank=True)
    oknok_5_13_remark = models.TextField(null=True, blank=True)
    oknok_5_14 = models.TextField(null=True, blank=True)
    oknok_5_14_soll = models.TextField(null=True, blank=True)
    oknok_5_14_remark = models.TextField(null=True, blank=True)
    oknok_5_15 = models.TextField(null=True, blank=True)
    oknok_5_15_soll = models.TextField(null=True, blank=True)
    oknok_5_15_remark = models.TextField(null=True, blank=True)
    oknok_5_16 = models.TextField(null=True, blank=True)
    oknok_5_16_soll = models.TextField(null=True, blank=True)
    oknok_5_16_remark = models.TextField(null=True, blank=True)
    oknok_5_17 = models.TextField(null=True, blank=True)
    oknok_5_17_soll = models.TextField(null=True, blank=True)
    oknok_5_17_remark = models.TextField(null=True, blank=True)
    oknok_5_18 = models.TextField(null=True, blank=True)
    oknok_5_18_soll = models.TextField(null=True, blank=True)
    oknok_5_18_remark = models.TextField(null=True, blank=True)
    oknok_5_19 = models.TextField(null=True, blank=True)
    oknok_5_19_soll = models.TextField(null=True, blank=True)
    oknok_5_19_remark = models.TextField(null=True, blank=True)
    oknok_5_20 = models.TextField(null=True, blank=True)
    oknok_5_20_soll = models.TextField(null=True, blank=True)
    oknok_5_20_remark = models.TextField(null=True, blank=True)
    oknok_5_21 = models.TextField(null=True, blank=True)
    oknok_5_21_soll = models.TextField(null=True, blank=True)
    oknok_5_21_remark = models.TextField(null=True, blank=True)
    oknok_5_22 = models.TextField(null=True, blank=True)
    oknok_5_22_soll = models.TextField(null=True, blank=True)
    oknok_5_22_remark = models.TextField(null=True, blank=True)
    oknok_5_23 = models.TextField(null=True, blank=True)
    oknok_5_23_soll = models.TextField(null=True, blank=True)
    oknok_5_23_remark = models.TextField(null=True, blank=True)
    oknok_5_24 = models.TextField(null=True, blank=True)
    oknok_5_24_soll = models.TextField(null=True, blank=True)
    oknok_5_24_remark = models.TextField(null=True, blank=True)
    oknok_5_25 = models.TextField(null=True, blank=True)
    oknok_5_25_soll = models.TextField(null=True, blank=True)
    oknok_5_25_remark = models.TextField(null=True, blank=True)
    oknok_5_26 = models.TextField(null=True, blank=True)
    oknok_5_26_soll = models.TextField(null=True, blank=True)
    oknok_5_26_remark = models.TextField(null=True, blank=True)
    oknok_5_27 = models.TextField(null=True, blank=True)
    oknok_5_27_soll = models.TextField(null=True, blank=True)
    oknok_5_27_remark = models.TextField(null=True, blank=True)
    oknok_5_28 = models.TextField(null=True, blank=True)
    oknok_5_28_soll = models.TextField(null=True, blank=True)
    oknok_5_28_remark = models.TextField(null=True, blank=True)
    oknok_5_29 = models.TextField(null=True, blank=True)
    oknok_5_29_soll = models.TextField(null=True, blank=True)
    oknok_5_29_remark = models.TextField(null=True, blank=True)
    oknok_5_30 = models.TextField(null=True, blank=True)
    oknok_5_30_soll = models.TextField(null=True, blank=True)
    oknok_5_30_remark = models.TextField(null=True, blank=True)
    oknok_5_31 = models.TextField(null=True, blank=True)
    oknok_5_31_soll = models.TextField(null=True, blank=True)
    oknok_5_31_remark = models.TextField(null=True, blank=True)
    oknok_5_32 = models.TextField(null=True, blank=True)
    oknok_5_32_soll = models.TextField(null=True, blank=True)
    oknok_5_32_remark = models.TextField(null=True, blank=True)
    oknok_5_33 = models.TextField(null=True, blank=True)
    oknok_5_33_soll = models.TextField(null=True, blank=True)
    oknok_5_33_remark = models.TextField(null=True, blank=True)
    oknok_5_34 = models.TextField(null=True, blank=True)
    oknok_5_34_soll = models.TextField(null=True, blank=True)
    oknok_5_34_remark = models.TextField(null=True, blank=True)
    oknok_5_35 = models.TextField(null=True, blank=True)
    oknok_5_35_soll = models.TextField(null=True, blank=True)
    oknok_5_35_remark = models.TextField(null=True, blank=True)
    oknok_5_36 = models.TextField(null=True, blank=True)
    oknok_5_36_soll = models.TextField(null=True, blank=True)
    oknok_5_36_remark = models.TextField(null=True, blank=True)
    oknok_5_37 = models.TextField(null=True, blank=True)
    oknok_5_37_soll = models.TextField(null=True, blank=True)
    oknok_5_37_remark = models.TextField(null=True, blank=True)
    oknok_5_38 = models.TextField(null=True, blank=True)
    oknok_5_38_soll = models.TextField(null=True, blank=True)
    oknok_5_38_remark = models.TextField(null=True, blank=True)
    oknok_5_39 = models.TextField(null=True, blank=True)
    oknok_5_39_soll = models.TextField(null=True, blank=True)
    oknok_5_39_remark = models.TextField(null=True, blank=True)
    oknok_5_40 = models.TextField(null=True, blank=True)
    oknok_5_40_soll = models.TextField(null=True, blank=True)
    oknok_5_40_remark = models.TextField(null=True, blank=True)
    oknok_5_41 = models.TextField(null=True, blank=True)
    oknok_5_41_soll = models.TextField(null=True, blank=True)
    oknok_5_41_remark = models.TextField(null=True, blank=True)
    oknok_5_42 = models.TextField(null=True, blank=True)
    oknok_5_42_soll = models.TextField(null=True, blank=True)
    oknok_5_42_remark = models.TextField(null=True, blank=True)
    oknok_5_43 = models.TextField(null=True, blank=True)
    oknok_5_43_soll = models.TextField(null=True, blank=True)
    oknok_5_43_remark = models.TextField(null=True, blank=True)
    oknok_5_44 = models.TextField(null=True, blank=True)
    oknok_5_44_soll = models.TextField(null=True, blank=True)
    oknok_5_44_remark = models.TextField(null=True, blank=True)
    oknok_5_45 = models.TextField(null=True, blank=True)
    oknok_5_45_soll = models.TextField(null=True, blank=True)
    oknok_5_45_remark = models.TextField(null=True, blank=True)
    oknok_5_46 = models.TextField(null=True, blank=True)
    oknok_5_46_soll = models.TextField(null=True, blank=True)
    oknok_5_46_remark = models.TextField(null=True, blank=True)
    oknok_5_47 = models.TextField(null=True, blank=True)
    oknok_5_47_soll = models.TextField(null=True, blank=True)
    oknok_5_47_remark = models.TextField(null=True, blank=True)
    oknok_5_48 = models.TextField(null=True, blank=True)
    oknok_5_48_soll = models.TextField(null=True, blank=True)
    oknok_5_48_remark = models.TextField(null=True, blank=True)
    oknok_5_49 = models.TextField(null=True, blank=True)
    oknok_5_49_soll = models.TextField(null=True, blank=True)
    oknok_5_49_remark = models.TextField(null=True, blank=True)
    oknok_5_50 = models.TextField(null=True, blank=True)
    oknok_5_50_soll = models.TextField(null=True, blank=True)
    oknok_5_50_remark = models.TextField(null=True, blank=True)
    oknok_5_51 = models.TextField(null=True, blank=True)
    oknok_5_51_soll = models.TextField(null=True, blank=True)
    oknok_5_51_remark = models.TextField(null=True, blank=True)
    oknok_6_1 = models.TextField(null=True, blank=True)
    oknok_6_1_soll = models.TextField(null=True, blank=True)
    oknok_6_1_remark = models.TextField(null=True, blank=True)
    oknok_6_2 = models.TextField(null=True, blank=True)
    oknok_6_2_soll = models.TextField(null=True, blank=True)
    oknok_6_2_remark = models.TextField(null=True, blank=True)
    oknok_6_3 = models.TextField(null=True, blank=True)
    oknok_6_3_soll = models.TextField(null=True, blank=True)
    oknok_6_3_remark = models.TextField(null=True, blank=True)
    oknok_6_4 = models.TextField(null=True, blank=True)
    oknok_6_4_soll = models.TextField(null=True, blank=True)
    oknok_6_4_remark = models.TextField(null=True, blank=True)
    oknok_6_5 = models.TextField(null=True, blank=True)
    oknok_6_5_soll = models.TextField(null=True, blank=True)
    oknok_6_5_remark = models.TextField(null=True, blank=True)
    oknok_6_6 = models.TextField(null=True, blank=True)
    oknok_6_6_soll = models.TextField(null=True, blank=True)
    oknok_6_6_remark = models.TextField(null=True, blank=True)
    oknok_6_7 = models.TextField(null=True, blank=True)
    oknok_6_7_soll = models.TextField(null=True, blank=True)
    oknok_6_7_remark = models.TextField(null=True, blank=True)
    oknok_6_8 = models.TextField(null=True, blank=True)
    oknok_6_8_soll = models.TextField(null=True, blank=True)
    oknok_6_8_remark = models.TextField(null=True, blank=True)
    oknok_6_9 = models.TextField(null=True, blank=True)
    oknok_6_9_soll = models.TextField(null=True, blank=True)
    oknok_6_9_remark = models.TextField(null=True, blank=True)
    oknok_6_10 = models.TextField(null=True, blank=True)
    oknok_6_10_soll = models.TextField(null=True, blank=True)
    oknok_6_10_remark = models.TextField(null=True, blank=True)
    oknok_6_11 = models.TextField(null=True, blank=True)
    oknok_6_11_soll = models.TextField(null=True, blank=True)
    oknok_6_11_remark = models.TextField(null=True, blank=True)
    oknok_6_12 = models.TextField(null=True, blank=True)
    oknok_6_12_soll = models.TextField(null=True, blank=True)
    oknok_6_12_remark = models.TextField(null=True, blank=True)
    oknok_6_13 = models.TextField(null=True, blank=True)
    oknok_6_13_soll = models.TextField(null=True, blank=True)
    oknok_6_13_remark = models.TextField(null=True, blank=True)
    oknok_7_1 = models.TextField(null=True, blank=True)
    oknok_7_1_soll = models.TextField(null=True, blank=True)
    oknok_7_1_remark = models.TextField(null=True, blank=True)
    oknok_7_2 = models.TextField(null=True, blank=True)
    oknok_7_2_soll = models.TextField(null=True, blank=True)
    oknok_7_2_remark = models.TextField(null=True, blank=True)
    oknok_7_3 = models.TextField(null=True, blank=True)
    oknok_7_3_soll = models.TextField(null=True, blank=True)
    oknok_7_3_remark = models.TextField(null=True, blank=True)
    oknok_7_4 = models.TextField(null=True, blank=True)
    oknok_7_4_soll = models.TextField(null=True, blank=True)
    oknok_7_4_remark = models.TextField(null=True, blank=True)
    oknok_8_1 = models.TextField(null=True, blank=True)
    oknok_8_1_soll = models.TextField(null=True, blank=True)
    oknok_8_1_remark = models.TextField(null=True, blank=True)
    oknok_8_2 = models.TextField(null=True, blank=True)
    oknok_8_2_soll = models.TextField(null=True, blank=True)
    oknok_8_2_remark = models.TextField(null=True, blank=True)
    oknok_8_3 = models.TextField(null=True, blank=True)
    oknok_8_3_soll = models.TextField(null=True, blank=True)
    oknok_8_3_remark = models.TextField(null=True, blank=True)
    oknok_8_4 = models.TextField(null=True, blank=True)
    oknok_8_4_soll = models.TextField(null=True, blank=True)
    oknok_8_4_remark = models.TextField(null=True, blank=True)
    oknok_8_5 = models.TextField(null=True, blank=True)
    oknok_8_5_soll = models.TextField(null=True, blank=True)
    oknok_8_5_remark = models.TextField(null=True, blank=True)
    oknok_10_1 = models.TextField(null=True, blank=True)
    oknok_10_1_soll = models.TextField(null=True, blank=True)
    oknok_10_1_remark = models.TextField(null=True, blank=True)
    oknok_10_2 = models.TextField(null=True, blank=True)
    oknok_10_2_soll = models.TextField(null=True, blank=True)
    oknok_10_2_remark = models.TextField(null=True, blank=True)
    oknok_10_3 = models.TextField(null=True, blank=True)
    oknok_10_3_soll = models.TextField(null=True, blank=True)
    oknok_10_3_remark = models.TextField(null=True, blank=True)
    oknok_10_4 = models.TextField(null=True, blank=True)
    oknok_10_4_soll = models.TextField(null=True, blank=True)
    oknok_10_4_remark = models.TextField(null=True, blank=True)
    oknok_10_5 = models.TextField(null=True, blank=True)
    oknok_10_5_soll = models.TextField(null=True, blank=True)
    oknok_10_5_remark = models.TextField(null=True, blank=True)

    oknok_1_8_lp = models.TextField(null=True, blank=True)
    oknok_1_29_lp = models.TextField(null=True, blank=True)
    oknok_1_35_lp = models.TextField(null=True, blank=True)
    oknok_1_36_lp = models.TextField(null=True, blank=True)
    oknok_2_13_lp = models.TextField(null=True, blank=True)
    oknok_2_14_lp = models.TextField(null=True, blank=True)
    oknok_3_1_lp = models.TextField(null=True, blank=True)
    oknok_3_31_lp = models.TextField(null=True, blank=True)
    oknok_3_32_lp = models.TextField(null=True, blank=True)
    oknok_4_13_lp = models.TextField(null=True, blank=True)
    oknok_4_14_lp = models.TextField(null=True, blank=True)
    oknok_5_26_lp = models.TextField(null=True, blank=True)
    oknok_5_29_lp = models.TextField(null=True, blank=True)
    oknok_5_30_lp = models.TextField(null=True, blank=True)
    oknok_5_35_lp = models.TextField(null=True, blank=True)
    oknok_5_38_lp = models.TextField(null=True, blank=True)
    oknok_5_46_lp = models.TextField(null=True, blank=True)
    oknok_5_47_lp = models.TextField(null=True, blank=True)
    oknok_5_50_lp = models.TextField(null=True, blank=True)
    oknok_5_51_lp = models.TextField(null=True, blank=True)
    oknok_6_12_lp = models.TextField(null=True, blank=True)
    oknok_6_13_lp = models.TextField(null=True, blank=True)
    oknok_8_1_lp = models.TextField(null=True, blank=True)
    oknok_8_2_lp = models.TextField(null=True, blank=True)
    oknok_8_3_lp = models.TextField(null=True, blank=True)
    oknok_8_4_lp = models.TextField(null=True, blank=True)
    oknok_8_5_lp = models.TextField(null=True, blank=True)


    check_size_1_21 = models.TextField(null=True, blank=True)
    check_size_1_21_soll = models.TextField(default = "461", null=True, blank=True)
    check_size_1_21_soll_avr = models.TextField(default = "1", null=True, blank=True)
    check_size_1_21_remark = models.TextField(null=True, blank=True)
    check_size_1_22 = models.TextField(null=True, blank=True)
    check_size_1_22_soll = models.TextField(default = "461", null=True, blank=True)
    check_size_1_22_soll_avr = models.TextField(default = "1", null=True, blank=True)
    check_size_1_22_remark = models.TextField(null=True, blank=True)
    check_size_3_7 = models.TextField(null=True, blank=True)
    check_size_3_7_soll = models.TextField(default = "10", null=True, blank=True)
    check_size_3_7_soll_avr = models.TextField(default = "3", null=True, blank=True)
    check_size_3_7_remark = models.TextField(null=True, blank=True)
    check_size_3_9 = models.TextField(null=True, blank=True)
    check_size_3_9_soll = models.TextField(default = "70", null=True, blank=True)
    check_size_3_9_soll_avr = models.TextField(default = "1", null=True, blank=True)
    check_size_3_9_remark = models.TextField(null=True, blank=True)


    text_4_5 = models.TextField(null=True, blank=True)
    text_4_5_remark = models.TextField(null=True, blank=True)
    text_7_5 = models.TextField(null=True, blank=True)
    text_7_5_remark = models.TextField(null=True, blank=True)
    text_7_6 = models.TextField(null=True, blank=True)
    text_7_6_remark = models.TextField(null=True, blank=True)
    text_9_1=models.TextField(null=True,blank=True)
    text_9_1_remark=models.TextField(null=True,blank=True)
    text_9_2=models.TextField(null=True,blank=True)
    text_9_2_remark=models.TextField(null=True,blank=True)
    text_9_3=models.TextField(null=True,blank=True)
    text_9_3_remark=models.TextField(null=True,blank=True)
    text_9_4=models.TextField(null=True,blank=True)
    text_9_4_remark=models.TextField(null=True,blank=True)
    text_9_5=models.TextField(null=True,blank=True)
    text_9_5_remark=models.TextField(null=True,blank=True)
    text_9_6=models.TextField(null=True,blank=True)
    text_9_6_remark=models.TextField(null=True,blank=True)
    text_9_7=models.TextField(null=True,blank=True)
    text_9_7_remark=models.TextField(null=True,blank=True)
    text_9_7_1=models.TextField(null=True,blank=True)
    text_9_7_1_remark=models.TextField(null=True,blank=True)
    text_9_7_2=models.TextField(null=True,blank=True)
    text_9_7_2_remark=models.TextField(null=True,blank=True)
    text_9_7_3=models.TextField(null=True,blank=True)
    text_9_7_3_remark=models.TextField(null=True,blank=True)
    text_9_7_4=models.TextField(null=True,blank=True)
    text_9_7_4_remark=models.TextField(null=True,blank=True)
    text_9_7_5=models.TextField(null=True,blank=True)
    text_9_7_5_remark=models.TextField(null=True,blank=True)
    text_9_7_6=models.TextField(null=True,blank=True)
    text_9_7_6_remark=models.TextField(null=True,blank=True)
    text_9_7_7=models.TextField(null=True,blank=True)
    text_9_7_7_remark=models.TextField(null=True,blank=True)
    text_9_7_8=models.TextField(null=True,blank=True)
    text_9_7_8_remark=models.TextField(null=True,blank=True)

    

    
    oknok_3_6 = models.TextField(verbose_name="1.1", null=True, blank=True)
    protocolName = models.CharField(max_length=255, default="Factory Out-Going inspection report")
    drawing = models.TextField(verbose_name="Zeichnung-Nr / Drawing No.", null=True, blank=True)
    rev = models.TextField(verbose_name="Rev", null=True, blank=True)
    order = models.TextField(verbose_name="Auftragsnr. / Order No.", null=True, blank=True)
    order_sag = models.TextField(verbose_name="Auftragsnr.-SAG / Order No.-SAG", null=True, blank=True)
    device = models.TextField(verbose_name="Geräte-Nr. / Device No.", null=True, blank=True)
    hoist = models.TextField(verbose_name="Hubzug-Nr. / Hoist No.", null=True, blank=True)
    company = models.TextField(verbose_name="Firma / Company", null=True, blank=True)
    quantity = models.TextField(verbose_name="Stückzahl / Quantity", null=True, blank=True)
    check_size_1 = models.TextField(verbose_name="Visual inspection of weldings, sampling, welding bend, check size of welding seams / EXC3", null=True, blank=True)
    oknok_size_1 = models.TextField(verbose_name="Tighten screws M12x65-8.8-A2F MA=93Nm", null=True, blank=True)
    check_size_3 = models.TextField(verbose_name="wooden block height between bottom of traverse and top of upper frameand lower frame. Front and Rear. Same heigth for all carriers", null=True, blank=True)
    check_size_4 = models.TextField(verbose_name="4. Durchmesser 2. Anschlussbohrung / Diameter of 2nd connecting hole", null=True, blank=True)
    check_size_4a = models.TextField(verbose_name="4a. Abstand zwischen Gehäuseseiten* / Distance between the frame sides *", null=True, blank=True)
    check_size_5 = models.TextField(verbose_name="5. Horizontaler Abstand zu Lochkreismitte für Lageranbau* / Horizontal distance to centre of drum bearing*", null=True, blank=True)
    check_size_6 = models.TextField(verbose_name="6. Vertikaler Abstand zu Lochkreismitte für Lageranbau* / Vertical distance to centre of drum bearing*", null=True, blank=True)
    check_size_7 = models.TextField(verbose_name="7. Durchmesser der Lagerbohrung* / Diameter of the holes for the bearings*", null=True, blank=True)
    check_size_8 = models.TextField(verbose_name="8. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)
    check_size_9 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)
    check_size_10 = models.TextField(verbose_name="10. Durchmesser der beiden Aufnahmebohrungen der Klinke / Diameter of both holes for the Catch lever", null=True, blank=True)
    position_tolerance_11 = models.TextField(verbose_name="11. Rechtwinkligkeit Trommellagerachse zu beiden Flächen der Seitenscheiben Pos. 1+2 / Right angle drum axle to both sides of the hoist frame Pos. 1 and Pos. 2", null=True, blank=True)
    check_size_1_soll =  models.TextField(default = "1230", null=True, blank=True)
    check_size_1_soll_avr =  models.TextField(default = "1.2", null=True, blank=True)
    oknok_size_1_soll =  models.TextField(default = "245", null=True, blank=True)
    check_size_2_soll_avr =  models.TextField(default = "0.5", null=True, blank=True)
    check_size_3_soll =  models.TextField(default = "23", null=True, blank=True)
    check_size_3_soll_avr =  models.TextField(default = "0.2", null=True, blank=True)
    check_size_4_soll =  models.TextField(default = "23", null=True, blank=True)
    check_size_4_soll_avr =  models.TextField(default = "0.2", null=True, blank=True)
    check_size_4a_soll =  models.TextField(default = "1156", null=True, blank=True)
    check_size_4a_soll_avr =  models.TextField(default = "0.5", null=True, blank=True)
    check_size_5_soll =  models.TextField(default = "300", null=True, blank=True)
    check_size_5_soll_avr =  models.TextField(default = "0.5", null=True, blank=True)
    check_size_6_soll =  models.TextField(default = "204", null=True, blank=True)
    check_size_6_soll_avr =  models.TextField(default = "0.5", null=True, blank=True)
    check_size_7_soll =  models.TextField(default = "150", null=True, blank=True)
    check_size_7_soll_avr =  models.TextField(default = "0.15", null=True, blank=True)
    check_size_8_soll =  models.TextField(default = "115", null=True, blank=True)
    check_size_8_soll_avr =  models.TextField(default = "0.1", null=True, blank=True)
    check_size_9_soll =  models.TextField(default = "150", null=True, blank=True)
    check_size_9_soll_avr =  models.TextField(default = "0.1", null=True, blank=True)
    check_size_10_soll =  models.TextField(default = "35", null=True, blank=True)
    check_size_10_soll_avr =  models.TextField(default = "0.025", null=True, blank=True)
    position_tolerance_11_soll =  models.TextField(default = "0.3", null=True, blank=True)
    position_tolerance_11_soll_avr =  models.TextField(default = "0", null=True, blank=True)
    miscellaneous = models.TextField(verbose_name="Sonstiges / Miscellaneous", blank=True, null=True)
    remark = models.TextField(verbose_name="Bemerkungen / Remarks", blank=True, null=True)
    measure = models.TextField(verbose_name="Messgerät / Measure tools", blank=True, null=True)
    date = models.CharField(verbose_name="Datum / Date", max_length=10, help_text="Format: dd.mm.yyyy", null=True, blank=True)
    inspector = models.CharField(verbose_name="Prüfer / Inspector", max_length=20, null=True, blank=True)
    department = models.TextField(verbose_name="Abteilung / Department", blank=True, null=True)
    last_changer = models.CharField(verbose_name="Last modified by", max_length=100, blank=True, null=True)
    baustelle = models.CharField(verbose_name="Baustelle", max_length=100, blank=True, null=True)

    additional_data = models.JSONField(default=dict, blank=True, null=True)
 
class ProtocolHubzugLaufSeiltrommel(models.Model):
    isSaved = models.BooleanField(default=False)
    isClosed = models.BooleanField(default=False)
    isExported = models.BooleanField(default=False)
    isCorrecturNeeded = models.BooleanField(default=False)

    protocolName  = models.CharField(max_length=255, default="Lauf Seiltrommel")
    drawing = models.TextField(verbose_name="Zeichnung-Nr / Drawing No.", null=True, blank=True)
    rev = models.TextField(verbose_name="Rev", null=True, blank=True)
    order = models.TextField(verbose_name="Auftragsnr. / Order No.", null=True, blank=True)
    order_sag = models.TextField(verbose_name="Auftragsnr.-SAG / Order No.-SAG", null=True, blank=True)
    component = models.TextField(verbose_name="Benennung/Component", null=True, blank=True)
    company = models.TextField(verbose_name="Firma / Company", null=True, blank=True)
    quantity = models.TextField(verbose_name="Stückzahl / Quantity", null=True, blank=True)
    baustelle = models.TextField(verbose_name="Baustelle", null=True, blank=True)
    check_size_1 = models.TextField(verbose_name="1. Horizontaler Abstand der Anschlussbohrungen* / Horizontal distance of connecting holes*", null=True, blank=True)
    check_size_2 = models.TextField(verbose_name="2. Vertikaler Abstand der Anschlussbohrungen / Vertical distance of connecting holes*", null=True, blank=True)
    check_size_3 = models.TextField(verbose_name="3. Durchmesser 1.Anschlussbohrung / Diameter of 1st connecting hole", null=True, blank=True)
    check_size_4 = models.TextField(verbose_name="4. Durchmesser 2. Anschlussbohrung / Diameter of 2nd connecting hole", null=True, blank=True)
    check_size_5 = models.TextField(verbose_name="5. Horizontaler Abstand zu Lochkreismitte für Lageranbau* / Horizontal distance to centre of drum bearing*", null=True, blank=True)
    check_size_6 = models.TextField(verbose_name="6. Vertikaler Abstand zu Lochkreismitte für Lageranbau* / Vertical distance to centre of drum bearing*", null=True, blank=True)
    check_size_7 = models.TextField(verbose_name="7. Durchmesser der Lagerbohrung* / Diameter of the holes for the bearings*", null=True, blank=True)
    check_size_8 = models.TextField(verbose_name="8. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)
    check_size_9 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)
    miscellaneous = models.TextField(verbose_name="Sonstiges / Miscellaneous", blank=True, null=True)
    remark = models.TextField(verbose_name="Bemerkungen / Remarks", blank=True, null=True)
    date = models.CharField(verbose_name="Datum / Date", max_length=10, help_text="Format: dd.mm.yyyy", null=True, blank=True)
    inspector = models.CharField(verbose_name="Prüfer / Inspector", max_length=20, null=True, blank=True)
    department = models.TextField(verbose_name="Abteilung / Department", blank=True, null=True)
    last_changer = models.CharField(verbose_name="Last modified by", max_length=100, blank=True, null=True)

class ProtocolHubzugMassSeiltrommel(models.Model):
    isSaved = models.BooleanField(default=False)
    isClosed = models.BooleanField(default=False)
    isExported = models.BooleanField(default=False)
    isCorrecturNeeded = models.BooleanField(default=False)

    protocolName  = models.CharField(max_length=255, default="Mass Seiltrommel")
    drawing = models.TextField(verbose_name="Zeichnung-Nr / Drawing No.", null=True, blank=True)
    rev = models.TextField(verbose_name="Rev", null=True, blank=True)
    order = models.TextField(verbose_name="Auftragsnr. / Order No.", null=True, blank=True)
    order_sag = models.TextField(verbose_name="Auftragsnr.-SAG / Order No.-SAG", null=True, blank=True)
    device = models.TextField(verbose_name="Device", null=True, blank=True)
    component = models.TextField(verbose_name="Benennung/Component", null=True, blank=True)
    company = models.TextField(verbose_name="Firma / Company", null=True, blank=True)
    quantity = models.TextField(verbose_name="Stückzahl / Quantity", null=True, blank=True)
    baustelle = models.TextField(verbose_name="Baustelle", null=True, blank=True)
    check_size_1 = models.TextField(verbose_name="1. Horizontaler Abstand der Anschlussbohrungen* / Horizontal distance of connecting holes*", null=True, blank=True)
    check_size_2 = models.TextField(verbose_name="2. Vertikaler Abstand der Anschlussbohrungen / Vertical distance of connecting holes*", null=True, blank=True)
    check_size_3 = models.TextField(verbose_name="3. Durchmesser 1.Anschlussbohrung / Diameter of 1st connecting hole", null=True, blank=True)
    check_size_4 = models.TextField(verbose_name="4. Durchmesser 2. Anschlussbohrung / Diameter of 2nd connecting hole", null=True, blank=True)
    check_size_5 = models.TextField(verbose_name="5. Horizontaler Abstand zu Lochkreismitte für Lageranbau* / Horizontal distance to centre of drum bearing*", null=True, blank=True)
    check_size_6 = models.TextField(verbose_name="6. Vertikaler Abstand zu Lochkreismitte für Lageranbau* / Vertical distance to centre of drum bearing*", null=True, blank=True)
    check_size_7 = models.TextField(verbose_name="7. Durchmesser der Lagerbohrung* / Diameter of the holes for the bearings*", null=True, blank=True)
    check_size_8 = models.TextField(verbose_name="8. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)
    check_size_9 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)
    check_size_10 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)
    check_size_11 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)
    check_size_12 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)
    check_size_13 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)    
    miscellaneous = models.TextField(verbose_name="Sonstiges / Miscellaneous", blank=True, null=True)
    remark = models.TextField(verbose_name="Bemerkungen / Remarks", blank=True, null=True)
    date = models.CharField(verbose_name="Datum / Date", max_length=10, help_text="Format: dd.mm.yyyy", null=True, blank=True)
    inspector = models.CharField(verbose_name="Prüfer / Inspector", max_length=20, null=True, blank=True)
    measure = models.CharField(verbose_name="Measure", max_length=20, null=True, blank=True)
    department = models.TextField(verbose_name="Abteilung / Department", blank=True, null=True)
    last_changer = models.CharField(verbose_name="Last modified by", max_length=100, blank=True, null=True)

class ProtocolLaufHubzug(models.Model):
    isSaved = models.BooleanField(default=False)
    isClosed = models.BooleanField(default=False)
    isExported = models.BooleanField(default=False)
    isCorrecturNeeded = models.BooleanField(default=False)
    isNacharbeiterNeeded = models.BooleanField(default=False)
    isPermanentDone = models.BooleanField(default=True)

    protocolName  = models.CharField(max_length=255, default="Einstellprotokoll tems BMW Leipzig A5E53621916A")
    drawing = models.TextField(verbose_name="Zeichnung-Nr / Drawing No.", null=True, blank=True)
    rev = models.TextField(verbose_name="Rev", null=True, blank=True)
    order = models.TextField(verbose_name="Auftragsnr. / Order No.", null=True, blank=True)
    order_sag = models.TextField(verbose_name="Auftragsnr.-SAG / Order No.-SAG", null=True, blank=True)
    device = models.TextField(verbose_name="Device", null=True, blank=True)
    component = models.TextField(verbose_name="Benennung/Component", null=True, blank=True)
    company = models.TextField(verbose_name="Firma / Company", null=True, blank=True)
    quantity = models.TextField(verbose_name="Stückzahl / Quantity", null=True, blank=True)
    baustelle = models.TextField(verbose_name="Baustelle", null=True, blank=True)
    hoist = models.TextField(verbose_name="Hoist", null=True, blank=True)
    loadTp = models.TextField(verbose_name="Load Tp", null=True, blank=True)
    check_size_1 = models.TextField(verbose_name="1. Horizontaler Abstand der Anschlussbohrungen* / Horizontal distance of connecting holes*", null=True, blank=True)
    check_size_2 = models.TextField(verbose_name="2. Vertikaler Abstand der Anschlussbohrungen / Vertical distance of connecting holes*", null=True, blank=True)
    check_size_3 = models.TextField(verbose_name="3. Durchmesser 1.Anschlussbohrung / Diameter of 1st connecting hole", null=True, blank=True)
    check_size_4 = models.TextField(verbose_name="4. Durchmesser 2. Anschlussbohrung / Diameter of 2nd connecting hole", null=True, blank=True)
    check_size_4a = models.TextField(verbose_name="4. Durchmesser 2. Anschlussbohrung / Diameter of 2nd connecting hole", null=True, blank=True)
    check_size_5 = models.TextField(verbose_name="5. Horizontaler Abstand zu Lochkreismitte für Lageranbau* / Horizontal distance to centre of drum bearing*", null=True, blank=True)
    check_size_6 = models.TextField(verbose_name="6. Vertikaler Abstand zu Lochkreismitte für Lageranbau* / Vertical distance to centre of drum bearing*", null=True, blank=True)
    check_size_7 = models.TextField(verbose_name="7. Durchmesser der Lagerbohrung* / Diameter of the holes for the bearings*", null=True, blank=True)
    check_size_8 = models.TextField(verbose_name="8. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)
    check_size_9 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)
    check_size_10 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)
    check_size_11 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)
    check_size_12 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)
    check_size_13 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)    
    check_size_14 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)    
    check_size_15 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)    
    check_size_16 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)    
    check_size_17 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)    
    check_size_18 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)    
    check_size_19 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)    
    check_size_20 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)    
    check_size_21 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)    
    check_size_22 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)    
    check_size_23 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)    

    miscellaneous = models.TextField(verbose_name="Sonstiges / Miscellaneous", blank=True, null=True)
    remark = models.TextField(verbose_name="Bemerkungen / Remarks", blank=True, null=True)
    date = models.CharField(verbose_name="Datum / Date", max_length=10, help_text="Format: dd.mm.yyyy", null=True, blank=True)
    inspector = models.CharField(verbose_name="Prüfer / Inspector", max_length=20, null=True, blank=True)
    measure = models.CharField(verbose_name="Measure", max_length=20, null=True, blank=True)
    department = models.TextField(verbose_name="Abteilung / Department", blank=True, null=True)
    last_changer = models.CharField(verbose_name="Last modified by", max_length=100, blank=True, null=True)

class ProtocolEndkontrolle(models.Model):
    isSaved = models.BooleanField(default=False)
    isClosed = models.BooleanField(default=False)
    isExported = models.BooleanField(default=False)
    isCorrecturNeeded = models.BooleanField(default=False)

    protocolName  = models.CharField(max_length=255, default="Endkontrolle")
    drawing = models.TextField(verbose_name="Zeichnung-Nr / Drawing No.", null=True, blank=True)
    rev = models.TextField(verbose_name="Rev", null=True, blank=True)
    order = models.TextField(verbose_name="Auftragsnr. / Order No.", null=True, blank=True)
    order_sag = models.TextField(verbose_name="Auftragsnr.-SAG / Order No.-SAG", null=True, blank=True)
    device = models.TextField(verbose_name="Device", null=True, blank=True)
    component = models.TextField(verbose_name="Benennung/Component", null=True, blank=True)
    company = models.TextField(verbose_name="Firma / Company", null=True, blank=True)
    quantity = models.TextField(verbose_name="Stückzahl / Quantity", null=True, blank=True)
    baustelle = models.TextField(verbose_name="Baustelle", null=True, blank=True)
    hoist = models.TextField(verbose_name="Hoist", null=True, blank=True)
    loadTp = models.TextField(verbose_name="Load Tp", null=True, blank=True)
    unitNO =  models.TextField(verbose_name="UnitNo", null=True, blank=True)
    check_size_1 = models.TextField(verbose_name="1. Horizontaler Abstand der Anschlussbohrungen* / Horizontal distance of connecting holes*", null=True, blank=True)
    check_size_2 = models.TextField(verbose_name="2. Vertikaler Abstand der Anschlussbohrungen / Vertical distance of connecting holes*", null=True, blank=True)
    check_size_3 = models.TextField(verbose_name="3. Durchmesser 1.Anschlussbohrung / Diameter of 1st connecting hole", null=True, blank=True)
    check_size_4 = models.TextField(verbose_name="4. Durchmesser 2. Anschlussbohrung / Diameter of 2nd connecting hole", null=True, blank=True)
    check_size_4a = models.TextField(verbose_name="4. Durchmesser 2. Anschlussbohrung / Diameter of 2nd connecting hole", null=True, blank=True)
    check_size_5 = models.TextField(verbose_name="5. Horizontaler Abstand zu Lochkreismitte für Lageranbau* / Horizontal distance to centre of drum bearing*", null=True, blank=True)
    check_size_5a = models.TextField(verbose_name="5. Horizontaler Abstand zu Lochkreismitte für Lageranbau* / Horizontal distance to centre of drum bearing*", null=True, blank=True)
    check_size_6 = models.TextField(verbose_name="6. Vertikaler Abstand zu Lochkreismitte für Lageranbau* / Vertical distance to centre of drum bearing*", null=True, blank=True)
    check_size_6a = models.TextField(verbose_name="5. Horizontaler Abstand zu Lochkreismitte für Lageranbau* / Horizontal distance to centre of drum bearing*", null=True, blank=True)
    check_size_7 = models.TextField(verbose_name="7. Durchmesser der Lagerbohrung* / Diameter of the holes for the bearings*", null=True, blank=True)
    check_size_8 = models.TextField(verbose_name="8. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)
    check_size_9 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)
    check_size_10 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)
    check_size_11 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)
    check_size_12 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)
    check_size_13 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)    
    check_size_14 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)    
    check_size_15 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)    
    check_size_16 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)    
    check_size_17 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)    
    check_size_18 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)    
    check_size_19 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)    
    check_size_20 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)    
    check_size_21 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)    
    check_size_22 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)    
    check_size_23 = models.TextField(verbose_name="9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever", null=True, blank=True)    

    miscellaneous = models.TextField(verbose_name="Sonstiges / Miscellaneous", blank=True, null=True)
    remark = models.TextField(verbose_name="Bemerkungen / Remarks", blank=True, null=True)
    date = models.CharField(verbose_name="Datum / Date", max_length=10, help_text="Format: dd.mm.yyyy", null=True, blank=True)
    inspector = models.CharField(verbose_name="Prüfer / Inspector", max_length=20, null=True, blank=True)
    measure = models.CharField(verbose_name="Measure", max_length=20, null=True, blank=True)
    department = models.TextField(verbose_name="Abteilung / Department", blank=True, null=True)
    last_changer = models.CharField(verbose_name="Last modified by", max_length=100, blank=True, null=True)

