# Generated by Django 4.2.1 on 2024-08-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pruefer',
            field=models.BooleanField(default=False),
        ),
    ]
