# Generated by Django 4.2.1 on 2024-08-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customuser_pruefer'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='isClosed',
            field=models.BooleanField(default=False),
        ),
    ]
