# Generated by Django 4.2.1 on 2024-08-08 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_protocolhubzugliftinghost_check_size_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newhubzug',
            old_name='hubzugInside',
            new_name='protocol1',
        ),
    ]
