# Generated by Django 4.2.1 on 2024-08-25 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_protocolhubzugliftinghost_isclosed'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='isCorrecturNeeded',
            field=models.BooleanField(default=False),
        ),
    ]
