# Generated by Django 4.2.1 on 2024-09-16 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_protocolhubzugliftinghost_iscorrecturneeded'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolHubzugLaufSeiltrommel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isSaved', models.BooleanField(default=False)),
                ('isClosed', models.BooleanField(default=False)),
                ('isExported', models.BooleanField(default=False)),
                ('isCorrecturNeeded', models.BooleanField(default=False)),
                ('drawing', models.TextField(blank=True, null=True, verbose_name='Zeichnung-Nr / Drawing No.')),
                ('rev', models.TextField(blank=True, null=True, verbose_name='Rev')),
                ('order', models.TextField(blank=True, null=True, verbose_name='Auftragsnr. / Order No.')),
                ('order_sag', models.TextField(blank=True, null=True, verbose_name='Auftragsnr.-SAG / Order No.-SAG')),
                ('device', models.TextField(blank=True, null=True, verbose_name='Geräte-Nr. / Device No.')),
                ('hoist', models.TextField(blank=True, null=True, verbose_name='Hubzug-Nr. / Hoist No.')),
                ('company', models.TextField(blank=True, null=True, verbose_name='Firma / Company')),
                ('quantity', models.TextField(blank=True, null=True, verbose_name='Stückzahl / Quantity')),
                ('check_size_1', models.TextField(blank=True, null=True, verbose_name='1. Horizontaler Abstand der Anschlussbohrungen* / Horizontal distance of connecting holes*')),
                ('check_size_2', models.TextField(blank=True, null=True, verbose_name='2. Vertikaler Abstand der Anschlussbohrungen / Vertical distance of connecting holes*')),
                ('check_size_3', models.TextField(blank=True, null=True, verbose_name='3. Durchmesser 1.Anschlussbohrung / Diameter of 1st connecting hole')),
                ('check_size_4', models.TextField(blank=True, null=True, verbose_name='4. Durchmesser 2. Anschlussbohrung / Diameter of 2nd connecting hole')),
                ('check_size_4a', models.TextField(blank=True, null=True, verbose_name='4a. Abstand zwischen Gehäuseseiten* / Distance between the frame sides *')),
                ('check_size_5', models.TextField(blank=True, null=True, verbose_name='5. Horizontaler Abstand zu Lochkreismitte für Lageranbau* / Horizontal distance to centre of drum bearing*')),
                ('check_size_6', models.TextField(blank=True, null=True, verbose_name='6. Vertikaler Abstand zu Lochkreismitte für Lageranbau* / Vertical distance to centre of drum bearing*')),
                ('check_size_7', models.TextField(blank=True, null=True, verbose_name='7. Durchmesser der Lagerbohrung* / Diameter of the holes for the bearings*')),
                ('check_size_8', models.TextField(blank=True, null=True, verbose_name='8. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever')),
                ('check_size_9', models.TextField(blank=True, null=True, verbose_name='9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever')),
                ('check_size_10', models.TextField(blank=True, null=True, verbose_name='10. Durchmesser der beiden Aufnahmebohrungen der Klinke / Diameter of both holes for the Catch lever')),
                ('position_tolerance_11', models.TextField(blank=True, null=True, verbose_name='11. Rechtwinkligkeit Trommellagerachse zu beiden Flächen der Seitenscheiben Pos. 1+2 / Right angle drum axle to both sides of the hoist frame Pos. 1 and Pos. 2')),
                ('miscellaneous', models.TextField(blank=True, null=True, verbose_name='Sonstiges / Miscellaneous')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='Bemerkungen / Remarks')),
                ('measure', models.TextField(blank=True, null=True, verbose_name='Messgerät / Measure tools')),
                ('date', models.CharField(blank=True, help_text='Format: dd.mm.yyyy', max_length=10, null=True, verbose_name='Datum / Date')),
                ('inspector', models.CharField(blank=True, max_length=20, null=True, verbose_name='Prüfer / Inspector')),
                ('department', models.TextField(blank=True, null=True, verbose_name='Abteilung / Department')),
                ('last_changer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Last modified by')),
                ('baustelle', models.CharField(blank=True, max_length=100, null=True, verbose_name='Baustelle')),
            ],
        ),
        migrations.AddField(
            model_name='newhubzug',
            name='protocol2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.protocolhubzuglaufseiltrommel'),
            preserve_default=False,
        ),
    ]
