# Generated by Django 4.2.1 on 2024-09-16 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_protocolhubzugmassseiltrommel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newhubzug',
            name='protocol1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.protocolhubzugliftinghost'),
        ),
        migrations.AlterField(
            model_name='newhubzug',
            name='protocol2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.protocolhubzuglaufseiltrommel'),
        ),
        migrations.AlterField(
            model_name='newhubzug',
            name='protocol3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.protocolhubzugmassseiltrommel'),
        ),
    ]
