# Generated by Django 4.2.1 on 2024-09-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_newhubzug_protocol1_alter_newhubzug_protocol2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocolhubzugmassseiltrommel',
            name='check_size_10',
        ),
        migrations.RemoveField(
            model_name='protocolhubzugmassseiltrommel',
            name='check_size_4a',
        ),
        migrations.RemoveField(
            model_name='protocolhubzugmassseiltrommel',
            name='device',
        ),
        migrations.RemoveField(
            model_name='protocolhubzugmassseiltrommel',
            name='hoist',
        ),
        migrations.RemoveField(
            model_name='protocolhubzugmassseiltrommel',
            name='measure',
        ),
        migrations.RemoveField(
            model_name='protocolhubzugmassseiltrommel',
            name='position_tolerance_11',
        ),
        migrations.AddField(
            model_name='protocolhubzugmassseiltrommel',
            name='component',
            field=models.TextField(blank=True, null=True, verbose_name='Benennung/Component'),
        ),
        migrations.AlterField(
            model_name='protocolhubzugmassseiltrommel',
            name='baustelle',
            field=models.TextField(blank=True, null=True, verbose_name='Baustelle'),
        ),
    ]
