# Generated by Django 4.2.1 on 2024-09-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_protocolhubzuglaufseiltrommel_check_size_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='protocolName',
            field=models.CharField(default='Maßkontrolle Rahmen', max_length=255),
        ),
    ]
