# Generated by Django 4.2.1 on 2024-09-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_protocolhubzugliftinghost_protocolname'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolhubzugmassseiltrommel',
            name='check_size_10',
            field=models.TextField(blank=True, null=True, verbose_name='9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever'),
        ),
        migrations.AddField(
            model_name='protocolhubzugmassseiltrommel',
            name='check_size_11',
            field=models.TextField(blank=True, null=True, verbose_name='9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever'),
        ),
        migrations.AddField(
            model_name='protocolhubzugmassseiltrommel',
            name='check_size_12',
            field=models.TextField(blank=True, null=True, verbose_name='9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever'),
        ),
        migrations.AddField(
            model_name='protocolhubzugmassseiltrommel',
            name='check_size_13',
            field=models.TextField(blank=True, null=True, verbose_name='9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever'),
        ),
        migrations.AddField(
            model_name='protocolhubzugmassseiltrommel',
            name='device',
            field=models.TextField(blank=True, null=True, verbose_name='Device'),
        ),
        migrations.AddField(
            model_name='protocolhubzugmassseiltrommel',
            name='measure',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Measure'),
        ),
    ]
