# Generated by Django 4.2.1 on 2024-10-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_protocolhubzugmassseiltrommel_check_size_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolhubzuglaufseiltrommel',
            name='protocolName',
            field=models.CharField(default='Lauf Seiltrommel', max_length=255),
        ),
        migrations.AddField(
            model_name='protocolhubzugmassseiltrommel',
            name='protocolName',
            field=models.CharField(default='Mass Seiltrommel', max_length=255),
        ),
    ]
