# Generated by Django 4.2.1 on 2024-11-07 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_protocolhubzuglaufseiltrommel_protocolname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolLaufHubzug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isSaved', models.BooleanField(default=False)),
                ('isClosed', models.BooleanField(default=False)),
                ('isExported', models.BooleanField(default=False)),
                ('isCorrecturNeeded', models.BooleanField(default=False)),
                ('protocolName', models.CharField(default='Mass Seiltrommel', max_length=255)),
                ('drawing', models.TextField(blank=True, null=True, verbose_name='Zeichnung-Nr / Drawing No.')),
                ('rev', models.TextField(blank=True, null=True, verbose_name='Rev')),
                ('order', models.TextField(blank=True, null=True, verbose_name='Auftragsnr. / Order No.')),
                ('order_sag', models.TextField(blank=True, null=True, verbose_name='Auftragsnr.-SAG / Order No.-SAG')),
                ('device', models.TextField(blank=True, null=True, verbose_name='Device')),
                ('component', models.TextField(blank=True, null=True, verbose_name='Benennung/Component')),
                ('company', models.TextField(blank=True, null=True, verbose_name='Firma / Company')),
                ('quantity', models.TextField(blank=True, null=True, verbose_name='Stückzahl / Quantity')),
                ('baustelle', models.TextField(blank=True, null=True, verbose_name='Baustelle')),
                ('check_size_1', models.TextField(blank=True, null=True, verbose_name='1. Horizontaler Abstand der Anschlussbohrungen* / Horizontal distance of connecting holes*')),
                ('check_size_2', models.TextField(blank=True, null=True, verbose_name='2. Vertikaler Abstand der Anschlussbohrungen / Vertical distance of connecting holes*')),
                ('check_size_3', models.TextField(blank=True, null=True, verbose_name='3. Durchmesser 1.Anschlussbohrung / Diameter of 1st connecting hole')),
                ('check_size_4', models.TextField(blank=True, null=True, verbose_name='4. Durchmesser 2. Anschlussbohrung / Diameter of 2nd connecting hole')),
                ('check_size_5', models.TextField(blank=True, null=True, verbose_name='5. Horizontaler Abstand zu Lochkreismitte für Lageranbau* / Horizontal distance to centre of drum bearing*')),
                ('check_size_6', models.TextField(blank=True, null=True, verbose_name='6. Vertikaler Abstand zu Lochkreismitte für Lageranbau* / Vertical distance to centre of drum bearing*')),
                ('check_size_7', models.TextField(blank=True, null=True, verbose_name='7. Durchmesser der Lagerbohrung* / Diameter of the holes for the bearings*')),
                ('check_size_8', models.TextField(blank=True, null=True, verbose_name='8. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever')),
                ('check_size_9', models.TextField(blank=True, null=True, verbose_name='9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever')),
                ('check_size_10', models.TextField(blank=True, null=True, verbose_name='9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever')),
                ('check_size_11', models.TextField(blank=True, null=True, verbose_name='9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever')),
                ('check_size_12', models.TextField(blank=True, null=True, verbose_name='9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever')),
                ('check_size_13', models.TextField(blank=True, null=True, verbose_name='9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever')),
                ('miscellaneous', models.TextField(blank=True, null=True, verbose_name='Sonstiges / Miscellaneous')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='Bemerkungen / Remarks')),
                ('date', models.CharField(blank=True, help_text='Format: dd.mm.yyyy', max_length=10, null=True, verbose_name='Datum / Date')),
                ('inspector', models.CharField(blank=True, max_length=20, null=True, verbose_name='Prüfer / Inspector')),
                ('measure', models.CharField(blank=True, max_length=20, null=True, verbose_name='Measure')),
                ('department', models.TextField(blank=True, null=True, verbose_name='Abteilung / Department')),
                ('last_changer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Last modified by')),
            ],
        ),
        migrations.AddField(
            model_name='newhubzug',
            name='protocol4',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.protocollaufhubzug'),
            preserve_default=False,
        ),
    ]
