# Generated by Django 4.2.1 on 2024-11-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_protocollaufhubzug_newhubzug_protocol4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocollaufhubzug',
            name='protocolName',
            field=models.CharField(default='Lauf Hubzug', max_length=255),
        ),
    ]
