# Generated by Django 4.2.1 on 2024-11-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_protocollaufhubzug_protocolname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocollaufhubzug',
            name='protocolName',
            field=models.CharField(default='Laufschein Hubzug', max_length=255),
        ),
    ]
