# Generated by Django 4.2.1 on 2024-11-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_protocollaufhubzug_protocolname'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocollaufhubzug',
            name='check_size_14',
            field=models.TextField(blank=True, null=True, verbose_name='9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever'),
        ),
        migrations.AddField(
            model_name='protocollaufhubzug',
            name='check_size_15',
            field=models.TextField(blank=True, null=True, verbose_name='9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever'),
        ),
        migrations.AddField(
            model_name='protocollaufhubzug',
            name='check_size_16',
            field=models.TextField(blank=True, null=True, verbose_name='9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever'),
        ),
        migrations.AddField(
            model_name='protocollaufhubzug',
            name='check_size_17',
            field=models.TextField(blank=True, null=True, verbose_name='9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever'),
        ),
        migrations.AddField(
            model_name='protocollaufhubzug',
            name='check_size_18',
            field=models.TextField(blank=True, null=True, verbose_name='9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever'),
        ),
        migrations.AddField(
            model_name='protocollaufhubzug',
            name='check_size_19',
            field=models.TextField(blank=True, null=True, verbose_name='9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever'),
        ),
        migrations.AddField(
            model_name='protocollaufhubzug',
            name='check_size_20',
            field=models.TextField(blank=True, null=True, verbose_name='9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever'),
        ),
        migrations.AddField(
            model_name='protocollaufhubzug',
            name='check_size_21',
            field=models.TextField(blank=True, null=True, verbose_name='9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever'),
        ),
        migrations.AddField(
            model_name='protocollaufhubzug',
            name='check_size_22',
            field=models.TextField(blank=True, null=True, verbose_name='9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever'),
        ),
        migrations.AddField(
            model_name='protocollaufhubzug',
            name='check_size_23',
            field=models.TextField(blank=True, null=True, verbose_name='9. Abstand zwischen Trommelachse und Bohrung für Klinke / Distance between centre of drum shaft and hole for catch lever'),
        ),
        migrations.AddField(
            model_name='protocollaufhubzug',
            name='check_size_4a',
            field=models.TextField(blank=True, null=True, verbose_name='4. Durchmesser 2. Anschlussbohrung / Diameter of 2nd connecting hole'),
        ),
        migrations.AddField(
            model_name='protocollaufhubzug',
            name='hoist',
            field=models.TextField(blank=True, null=True, verbose_name='Hoist'),
        ),
        migrations.AddField(
            model_name='protocollaufhubzug',
            name='loadTp',
            field=models.TextField(blank=True, null=True, verbose_name='Load Tp'),
        ),
    ]
