# Generated by Django 4.2.1 on 2024-11-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_protocolendkontrolle_newhubzug_protocol5'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolendkontrolle',
            name='check_size_5a',
            field=models.TextField(blank=True, null=True, verbose_name='5. Horizontaler Abstand zu Lochkreismitte für Lageranbau* / Horizontal distance to centre of drum bearing*'),
        ),
        migrations.AddField(
            model_name='protocolendkontrolle',
            name='check_size_6a',
            field=models.TextField(blank=True, null=True, verbose_name='5. Horizontaler Abstand zu Lochkreismitte für Lageranbau* / Horizontal distance to centre of drum bearing*'),
        ),
        migrations.AddField(
            model_name='protocolendkontrolle',
            name='unitNO',
            field=models.TextField(blank=True, null=True, verbose_name='UnitNo'),
        ),
    ]
