# Generated by Django 4.2.1 on 2024-11-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_protocolendkontrolle_check_size_5a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='check_size_1_soll',
            field=models.TextField(blank=True, default='1230', null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='check_size_1_soll_avr',
            field=models.TextField(blank=True, default='1,2', null=True),
        ),
    ]
