# Generated by Django 4.2.1 on 2024-11-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_protocolhubzugliftinghost_check_size_1_soll_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='check_size_10_soll',
            field=models.TextField(blank=True, default='35', null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='check_size_10_soll_avr',
            field=models.TextField(blank=True, default='0,025', null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='check_size_11_soll',
            field=models.TextField(blank=True, default='0,3', null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='check_size_11_soll_avr',
            field=models.TextField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='check_size_2_soll',
            field=models.TextField(blank=True, default='245', null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='check_size_2_soll_avr',
            field=models.TextField(blank=True, default='0,5', null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='check_size_3_soll',
            field=models.TextField(blank=True, default='23', null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='check_size_3_soll_avr',
            field=models.TextField(blank=True, default='0,2', null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='check_size_4_soll',
            field=models.TextField(blank=True, default='23', null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='check_size_4_soll_avr',
            field=models.TextField(blank=True, default='0,2', null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='check_size_4a_soll',
            field=models.TextField(blank=True, default='1156', null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='check_size_4a_soll_avr',
            field=models.TextField(blank=True, default='0,5', null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='check_size_5_soll',
            field=models.TextField(blank=True, default='300', null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='check_size_5_soll_avr',
            field=models.TextField(blank=True, default='0,5', null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='check_size_6_soll',
            field=models.TextField(blank=True, default='204', null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='check_size_6_soll_avr',
            field=models.TextField(blank=True, default='0,5', null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='check_size_7_soll',
            field=models.TextField(blank=True, default='150', null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='check_size_7_soll_avr',
            field=models.TextField(blank=True, default='0,15', null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='check_size_8_soll',
            field=models.TextField(blank=True, default='115', null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='check_size_8_soll_avr',
            field=models.TextField(blank=True, default='0,1', null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='check_size_9_soll',
            field=models.TextField(blank=True, default='150', null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='check_size_9_soll_avr',
            field=models.TextField(blank=True, default='0,1', null=True),
        ),
    ]
