# Generated by Django 4.2.1 on 2024-11-26 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_protocolhubzugliftinghost_check_size_10_soll_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='check_size_11_soll',
            new_name='position_tolerance_11_soll',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='check_size_11_soll_avr',
            new_name='position_tolerance_11_soll_avr',
        ),
    ]
