# Generated by Django 4.2.1 on 2025-01-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_rename_check_size_11_soll_protocolhubzugliftinghost_position_tolerance_11_soll_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocollaufhubzug',
            name='isNacharbeiterNeeded',
            field=models.BooleanField(default=False),
        ),
    ]
