# Generated by Django 4.2.1 on 2025-02-02 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_protocollaufhubzug_isnacharbeiterneeded'),
    ]

    operations = [
        migrations.CreateModel(
            name='permanentProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permanentProtocolName', models.CharField(max_length=30)),
                ('protocol1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.protocolhubzugliftinghost')),
                ('protocol2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.protocolhubzuglaufseiltrommel')),
                ('protocol3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.protocolhubzugmassseiltrommel')),
                ('protocol4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.protocollaufhubzug')),
                ('protocol5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.protocolendkontrolle')),
            ],
        ),
    ]
