# Generated by Django 4.2.1 on 2025-02-02 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_permanentprotocol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permanentprotocol',
            name='protocol1',
        ),
        migrations.RemoveField(
            model_name='permanentprotocol',
            name='protocol2',
        ),
        migrations.RemoveField(
            model_name='permanentprotocol',
            name='protocol3',
        ),
        migrations.RemoveField(
            model_name='permanentprotocol',
            name='protocol4',
        ),
        migrations.RemoveField(
            model_name='permanentprotocol',
            name='protocol5',
        ),
    ]
