# Generated by Django 4.2.1 on 2025-02-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_remove_permanentprotocol_protocol1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permanentprotocol',
            name='protocol1',
            field=models.ManyToManyField(to='myapp.protocolhubzugliftinghost'),
        ),
    ]
