# Generated by Django 4.2.1 on 2025-02-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_permanentprotocol_protocol1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permanentprotocol',
            name='protocol1',
            field=models.ManyToManyField(related_name='permanent_protocols', to='myapp.protocolhubzugliftinghost'),
        ),
    ]
