# Generated by Django 5.1.6 on 2025-02-14 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_permanentprotocol_protocol1'),
    ]

    operations = [
        migrations.AddField(
            model_name='permanentprotocol',
            name='permanentProtocol1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.protocolhubzugliftinghost'),
            preserve_default=False,
        ),
    ]
