# Generated by Django 5.1.6 on 2025-02-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_permanentprotocol_permanentprotocol1'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='isPermanentDone',
            field=models.BooleanField(default=False),
        ),
    ]
