# Generated by Django 5.1.6 on 2025-02-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_protocolhubzugliftinghost_ispermanentdone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolhubzugliftinghost',
            name='check_size_1_soll_avr',
            field=models.TextField(blank=True, default='1.2', null=True),
        ),
    ]
