# Generated by Django 4.2.1 on 2025-02-15 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_protocolhubzugliftinghost_check_size_1_soll_avr'),
    ]

    operations = [
        migrations.AddField(
            model_name='permanentprotocol',
            name='permanentProtocol4',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.protocollaufhubzug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permanentprotocol',
            name='protocol4',
            field=models.ManyToManyField(related_name='permanent_protocols', to='myapp.protocollaufhubzug'),
        ),
        migrations.AddField(
            model_name='protocollaufhubzug',
            name='isPermanentDone',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='protocolhubzugliftinghost',
            name='check_size_10_soll_avr',
            field=models.TextField(blank=True, default='0.025', null=True),
        ),
        migrations.AlterField(
            model_name='protocolhubzugliftinghost',
            name='check_size_2_soll_avr',
            field=models.TextField(blank=True, default='0.5', null=True),
        ),
        migrations.AlterField(
            model_name='protocolhubzugliftinghost',
            name='check_size_3_soll_avr',
            field=models.TextField(blank=True, default='0.2', null=True),
        ),
        migrations.AlterField(
            model_name='protocolhubzugliftinghost',
            name='check_size_4_soll_avr',
            field=models.TextField(blank=True, default='0.2', null=True),
        ),
        migrations.AlterField(
            model_name='protocolhubzugliftinghost',
            name='check_size_4a_soll_avr',
            field=models.TextField(blank=True, default='0.5', null=True),
        ),
        migrations.AlterField(
            model_name='protocolhubzugliftinghost',
            name='check_size_5_soll_avr',
            field=models.TextField(blank=True, default='0.5', null=True),
        ),
        migrations.AlterField(
            model_name='protocolhubzugliftinghost',
            name='check_size_6_soll_avr',
            field=models.TextField(blank=True, default='0.5', null=True),
        ),
        migrations.AlterField(
            model_name='protocolhubzugliftinghost',
            name='check_size_7_soll_avr',
            field=models.TextField(blank=True, default='0.15', null=True),
        ),
        migrations.AlterField(
            model_name='protocolhubzugliftinghost',
            name='check_size_8_soll_avr',
            field=models.TextField(blank=True, default='0.1', null=True),
        ),
        migrations.AlterField(
            model_name='protocolhubzugliftinghost',
            name='check_size_9_soll_avr',
            field=models.TextField(blank=True, default='0.1', null=True),
        ),
        migrations.AlterField(
            model_name='protocolhubzugliftinghost',
            name='position_tolerance_11_soll',
            field=models.TextField(blank=True, default='0.3', null=True),
        ),
    ]
