# Generated by Django 4.2.1 on 2025-03-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_permanentprotocol_permanentprotocol4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='additional_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
