# Generated by Django 4.2.1 on 2025-03-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_protocolhubzugliftinghost_additional_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='baustellen',
            field=models.ManyToManyField(related_name='baustellen', to='myapp.newbaustelle'),
        ),
    ]
