# Generated by Django 4.2.1 on 2025-04-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_customuser_baustellen'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='elektrik',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hubzug',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mechanik',
            field=models.BooleanField(default=False),
        ),
    ]
