# Generated by Django 4.2.1 on 2025-04-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_customuser_elektrik_customuser_hubzug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='count',
            field=models.PositiveIntegerField(default=12),
        ),
    ]
