# Generated by Django 4.2.1 on 2025-05-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_protocolhubzugliftinghost_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='isNacharbeitNeeded',
            field=models.BooleanField(default=False),
        ),
    ]
