# Generated by Django 5.2.4 on 2025-10-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_protocolhubzugliftinghost_isnacharbeitneeded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolhubzugliftinghost',
            name='check_size_1',
            field=models.TextField(blank=True, null=True, verbose_name='Visual inspection of weldings, sampling, welding bend, check size of welding seams / EXC3'),
        ),
    ]
