# Generated by Django 5.2.4 on 2025-10-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_alter_protocolhubzugliftinghost_check_size_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocolhubzugliftinghost',
            name='check_size_2',
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_size_1',
            field=models.TextField(blank=True, null=True, verbose_name='Tighten screws M12x65-8.8-A2F MA=93Nm'),
        ),
        migrations.AlterField(
            model_name='protocolhubzugliftinghost',
            name='check_size_3',
            field=models.TextField(blank=True, null=True, verbose_name='wooden block height between bottom of traverse and top of upper frameand lower frame. Front and Rear. Same heigth for all carriers'),
        ),
    ]
