# Generated by Django 5.2.4 on 2025-10-12 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_remove_protocolhubzugliftinghost_check_size_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='check_size_2_soll',
            new_name='oknok_size_1_soll',
        ),
    ]
