# Generated by Django 5.2.4 on 2025-10-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_rename_check_size_2_soll_protocolhubzugliftinghost_oknok_size_1_soll'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='check_size_10_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='check_size_10_2_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='check_size_10_2_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='check_size_10_2_soll_avr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_6',
            field=models.TextField(blank=True, null=True, verbose_name='1.1'),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_6_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_6_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_1_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_1_1_remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
