# Generated by Django 5.2.4 on 2025-11-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_protocolhubzugliftinghost_check_size_10_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_1_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_1_2_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='protocolhubzugliftinghost',
            name='check_size_10_2_soll',
            field=models.TextField(blank=True, default='245', null=True),
        ),
        migrations.AlterField(
            model_name='protocolhubzugliftinghost',
            name='check_size_10_2_soll_avr',
            field=models.TextField(blank=True, default='3', null=True),
        ),
        migrations.AlterField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_6_soll',
            field=models.TextField(blank=True, default='93', null=True),
        ),
    ]
