# Generated by Django 5.2.4 on 2025-11-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_protocolhubzugliftinghost_text_1_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_7_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_7_soll',
            field=models.TextField(blank=True, default='55', null=True),
        ),
    ]
