# Generated by Django 5.2.4 on 2025-11-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_protocolhubzugliftinghost_oknok_1_7_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_1_11',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_1_11_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_1_24',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_1_24_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_1_25',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_1_25_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_1_26',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_1_26_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_1_28',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_1_28_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_1_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_1_33',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_1_33_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_1_34',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_1_34_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_1_35',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_1_35_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_1_36',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_1_36_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_1_3_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_1_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_1_5_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_1_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_1_6_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_1_8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_1_8_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_1_9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_1_9_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_2_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_2_11',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_2_11_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_2_13',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_2_13_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_2_14',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_2_14_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_2_1_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_2_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_2_2_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_2_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_2_3_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_2_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_2_4_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_2_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_2_5_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_2_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_2_6_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_2_7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_2_7_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_2_8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_2_8_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_3_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_3_11',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_3_11_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_3_12',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_3_12_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_3_13',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_3_13_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_3_14',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_3_14_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_3_15',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_3_15_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_3_16',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_3_16_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_3_18',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_3_18_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_3_19',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_3_19_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_3_1_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_3_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_3_22',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_3_22_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_3_23',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_3_23_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_3_24',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_3_24_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_3_25',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_3_25_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_3_26',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_3_26_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_3_28',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_3_28_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_3_29',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_3_29_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_3_2_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_3_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_3_31',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_3_31_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_3_32',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_3_32_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_3_3_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_3_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_3_4_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_3_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_3_5_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_3_8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_3_8_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_4_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_4_1_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_4_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_4_3_remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
