# Generated by Django 5.2.4 on 2025-11-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_protocolhubzugliftinghost_text_1_11_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_12',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_12_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_12_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_13',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_13_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_13_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_15',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_15_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_15_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_16',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_16_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_16_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_18',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_18_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_18_soll',
            field=models.TextField(blank=True, default='11', null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_19',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_19_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_19_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_1_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_1_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_21',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_21_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_21_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_22',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_22_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_22_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_23',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_23_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_23_soll',
            field=models.TextField(blank=True, default='18', null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_27',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_27_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_27_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_29',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_29_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_29_soll',
            field=models.TextField(blank=True, default='10', null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_2_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_2_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_31',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_31_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_31_soll',
            field=models.TextField(blank=True, default='27', null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_32',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_32_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_32_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_2_12',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_2_12_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_2_12_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_2_9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_2_9_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_2_9_soll',
            field=models.TextField(blank=True, default='2', null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_21',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_21_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_21_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_27',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_27_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_27_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_9_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_9_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_4_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_4_2_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_4_2_soll',
            field=models.TextField(blank=True, default='4', null=True),
        ),
    ]
