# Generated by Django 5.2.4 on 2025-12-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_protocolhubzugliftinghost_oknok_1_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='check_size_10_2',
            new_name='check_size_1_21',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='check_size_10_2_remark',
            new_name='check_size_1_21_remark',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='oknok_1_21',
            new_name='check_size_1_22',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='oknok_1_21_remark',
            new_name='check_size_1_22_remark',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='oknok_1_21_soll',
            new_name='check_size_3_7',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='oknok_1_22',
            new_name='check_size_3_7_remark',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='check_size_10_2_soll_avr',
            new_name='check_size_3_7_soll_avr',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='oknok_1_22_remark',
            new_name='check_size_3_9',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='oknok_1_22_soll',
            new_name='check_size_3_9_remark',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='oknok_3_9',
            new_name='oknok_10_1',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='oknok_3_9_remark',
            new_name='oknok_10_1_remark',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='oknok_3_9_soll',
            new_name='oknok_10_1_soll',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_1_1',
            new_name='oknok_10_2',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_1_11',
            new_name='oknok_10_2_remark',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_1_11_remark',
            new_name='oknok_10_2_soll',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_1_1_remark',
            new_name='oknok_10_3',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_1_2',
            new_name='oknok_10_3_remark',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_1_24',
            new_name='oknok_10_3_soll',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_1_24_remark',
            new_name='oknok_10_4',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_1_25',
            new_name='oknok_10_4_remark',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_1_25_remark',
            new_name='oknok_10_4_soll',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_1_26',
            new_name='oknok_10_5',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_1_26_remark',
            new_name='oknok_10_5_remark',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_1_28',
            new_name='oknok_10_5_soll',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_1_28_remark',
            new_name='oknok_1_10',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_1_2_remark',
            new_name='oknok_1_10_remark',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_1_3',
            new_name='oknok_1_10_soll',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_1_33',
            new_name='oknok_1_11',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_1_33_remark',
            new_name='oknok_1_11_remark',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_1_34_remark',
            new_name='oknok_1_11_soll',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_1_34',
            new_name='oknok_1_14',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_1_35',
            new_name='oknok_1_14_remark',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_1_35_remark',
            new_name='oknok_1_14_soll',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_1_36',
            new_name='oknok_1_17',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_1_36_remark',
            new_name='oknok_1_17_remark',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_1_3_remark',
            new_name='oknok_1_17_soll',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_1_5',
            new_name='oknok_1_20',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_1_5_remark',
            new_name='oknok_1_20_remark',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_1_6',
            new_name='oknok_1_20_soll',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_1_6_remark',
            new_name='oknok_1_24',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_1_8',
            new_name='oknok_1_24_remark',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_1_8_remark',
            new_name='oknok_1_24_soll',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_1_9',
            new_name='oknok_1_25',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_1_9_remark',
            new_name='oknok_1_25_remark',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_2_1',
            new_name='oknok_1_25_soll',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_2_11',
            new_name='oknok_1_26',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_2_11_remark',
            new_name='oknok_1_26_remark',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_2_13',
            new_name='oknok_1_26_soll',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_2_13_remark',
            new_name='oknok_1_28',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_2_14',
            new_name='oknok_1_28_remark',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_2_14_remark',
            new_name='oknok_1_28_soll',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_2_1_remark',
            new_name='oknok_1_3',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_2_2',
            new_name='oknok_1_30',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_2_2_remark',
            new_name='oknok_1_30_remark',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_2_3',
            new_name='oknok_1_30_soll',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_2_3_remark',
            new_name='oknok_1_33',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_2_4',
            new_name='oknok_1_33_remark',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_2_4_remark',
            new_name='oknok_1_33_soll',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_2_5',
            new_name='oknok_1_34',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_2_5_remark',
            new_name='oknok_1_34_remark',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_2_6',
            new_name='oknok_1_34_soll',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_2_6_remark',
            new_name='oknok_1_35',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_2_7',
            new_name='oknok_1_35_remark',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_2_7_remark',
            new_name='oknok_1_35_soll',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_2_8',
            new_name='oknok_1_36',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_2_8_remark',
            new_name='oknok_1_36_remark',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_3_1',
            new_name='oknok_1_36_soll',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_3_11',
            new_name='oknok_1_3_remark',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_3_11_remark',
            new_name='oknok_1_3_soll',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_3_12',
            new_name='oknok_1_4',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_3_12_remark',
            new_name='oknok_1_4_remark',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_3_13',
            new_name='oknok_1_4_soll',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_3_13_remark',
            new_name='oknok_1_5',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_3_14',
            new_name='oknok_1_5_remark',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_3_14_remark',
            new_name='oknok_1_5_soll',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_3_15',
            new_name='oknok_1_6',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_3_15_remark',
            new_name='oknok_1_6_remark',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_3_16',
            new_name='oknok_1_6_soll',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_3_16_remark',
            new_name='oknok_1_8',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_3_18',
            new_name='oknok_1_8_remark',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_3_19',
            new_name='oknok_1_8_soll',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_3_18_remark',
            new_name='oknok_1_9',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_3_19_remark',
            new_name='oknok_1_9_remark',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_3_1_remark',
            new_name='oknok_1_9_soll',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_3_2',
            new_name='oknok_2_1',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_3_22',
            new_name='oknok_2_10',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_3_22_remark',
            new_name='oknok_2_10_remark',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_3_23',
            new_name='oknok_2_10_soll',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_3_24',
            new_name='oknok_2_11',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_3_23_remark',
            new_name='oknok_2_11_remark',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_3_24_remark',
            new_name='oknok_2_11_soll',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_3_25',
            new_name='oknok_2_13',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_3_26',
            new_name='oknok_2_13_remark',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_3_25_remark',
            new_name='oknok_2_13_soll',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_3_26_remark',
            new_name='oknok_2_14',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_3_28',
            new_name='oknok_2_14_remark',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_3_28_remark',
            new_name='oknok_2_14_soll',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_3_29_remark',
            new_name='oknok_2_1_remark',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_3_29',
            new_name='oknok_2_1_soll',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_3_2_remark',
            new_name='oknok_2_2',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_3_3',
            new_name='oknok_2_2_remark',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_3_31',
            new_name='oknok_2_2_soll',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_3_31_remark',
            new_name='oknok_2_3',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_3_32_remark',
            new_name='oknok_2_3_remark',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_3_32',
            new_name='oknok_2_3_soll',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_3_3_remark',
            new_name='oknok_2_4',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_3_4',
            new_name='oknok_2_4_remark',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_3_4_remark',
            new_name='oknok_2_4_soll',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_3_5_remark',
            new_name='oknok_2_5',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_3_5',
            new_name='oknok_2_5_remark',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_3_8',
            new_name='oknok_2_5_soll',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_3_8_remark',
            new_name='oknok_2_6',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_4_1',
            new_name='oknok_2_6_remark',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_4_1_remark',
            new_name='oknok_2_6_soll',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_4_3',
            new_name='oknok_2_7',
        ),
        migrations.RenameField(
            model_name='protocolhubzugliftinghost',
            old_name='text_4_3_remark',
            new_name='oknok_2_7_remark',
        ),
        migrations.RemoveField(
            model_name='protocolhubzugliftinghost',
            name='check_size_10_2_soll',
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='check_size_1_21_soll',
            field=models.TextField(blank=True, default='461', null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='check_size_1_21_soll_avr',
            field=models.TextField(blank=True, default='1', null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='check_size_1_22_soll',
            field=models.TextField(blank=True, default='461', null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='check_size_1_22_soll_avr',
            field=models.TextField(blank=True, default='1', null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='check_size_3_7_soll',
            field=models.TextField(blank=True, default='10', null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='check_size_3_9_soll',
            field=models.TextField(blank=True, default='70', null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='check_size_3_9_soll_avr',
            field=models.TextField(blank=True, default='1', null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_2_7_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_2_8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_2_8_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_2_8_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_10_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_10_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_11',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_11_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_11_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_12',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_12_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_12_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_13',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_13_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_13_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_14',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_14_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_14_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_15',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_15_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_15_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_16',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_16_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_16_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_17',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_17_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_17_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_18',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_18_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_18_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_19',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_19_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_19_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_1_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_1_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_20',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_20_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_20_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_22',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_22_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_22_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_23',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_23_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_23_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_24',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_24_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_24_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_25',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_25_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_25_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_26',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_26_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_26_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_28',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_28_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_28_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_29',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_29_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_29_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_2_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_2_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_30',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_30_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_30_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_31',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_31_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_31_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_32',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_32_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_32_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_3_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_3_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_4_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_4_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_5_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_5_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_8_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_8_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_4_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_4_10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_4_10_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_4_10_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_4_11',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_4_11_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_4_11_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_4_12',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_4_12_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_4_12_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_4_13',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_4_13_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_4_13_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_4_14',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_4_14_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_4_14_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_4_1_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_4_1_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_4_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_4_3_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_4_3_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_4_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_4_4_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_4_4_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_4_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_4_6_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_4_6_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_4_7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_4_7_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_4_7_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_4_8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_4_8_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_4_8_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_4_9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_4_9_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_4_9_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_10_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_10_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_11',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_11_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_11_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_12',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_12_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_12_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_13',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_13_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_13_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_14',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_14_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_14_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_15',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_15_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_15_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_16',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_16_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_16_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_17',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_17_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_17_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_18',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_18_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_18_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_19',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_19_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_19_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_1_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_1_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_20',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_20_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_20_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_21',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_21_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_21_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_22',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_22_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_22_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_23',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_23_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_23_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_24',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_24_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_24_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_25',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_25_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_25_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_26',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_26_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_26_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_27',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_27_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_27_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_28',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_28_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_28_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_29',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_29_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_29_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_2_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_2_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_30',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_30_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_30_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_31',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_31_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_31_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_32',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_32_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_32_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_33',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_33_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_33_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_34',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_34_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_34_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_35',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_35_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_35_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_36',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_36_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_36_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_37',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_37_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_37_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_38',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_38_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_38_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_39',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_39_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_39_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_3_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_3_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_40',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_40_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_40_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_41',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_41_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_41_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_42',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_42_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_42_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_43',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_43_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_43_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_44',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_44_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_44_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_45',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_45_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_45_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_46',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_46_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_46_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_47',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_47_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_47_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_48',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_48_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_48_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_49',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_49_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_49_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_4_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_4_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_50',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_50_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_50_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_51',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_51_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_51_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_5_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_5_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_6_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_6_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_7_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_7_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_8_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_8_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_9_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_5_9_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_6_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_6_10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_6_10_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_6_10_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_6_11',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_6_11_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_6_11_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_6_12',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_6_12_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_6_12_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_6_13',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_6_13_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_6_13_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_6_1_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_6_1_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_6_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_6_2_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_6_2_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_6_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_6_3_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_6_3_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_6_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_6_4_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_6_4_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_6_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_6_5_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_6_5_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_6_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_6_6_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_6_6_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_6_7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_6_7_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_6_7_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_6_8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_6_8_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_6_8_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_6_9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_6_9_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_6_9_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_7_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_7_1_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_7_1_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_7_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_7_2_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_7_2_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_7_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_7_3_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_7_3_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_7_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_7_4_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_7_4_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_8_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_8_1_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_8_1_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_8_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_8_2_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_8_2_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_8_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_8_3_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_8_3_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_8_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_8_4_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_8_4_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_8_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_8_5_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='oknok_8_5_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_4_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_4_5_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_7_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_7_5_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_7_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_7_6_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_9_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_9_1_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_9_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_9_2_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_9_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_9_3_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_9_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_9_4_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_9_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_9_5_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_9_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_9_6_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_9_7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_9_7_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_9_7_1_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_9_7_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_9_7_2_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_9_7_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_9_7_3_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_9_7_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_9_7_4_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_9_7_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_9_7_5_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_9_7_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_9_7_6_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_9_7_7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_9_7_7_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_9_7_8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_9_7_8_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocolhubzugliftinghost',
            name='text_9_7_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_18_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_23_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_29_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_31_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_7_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='protocolhubzugliftinghost',
            name='oknok_2_9_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='protocolhubzugliftinghost',
            name='oknok_3_6_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='protocolhubzugliftinghost',
            name='oknok_4_2_soll',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='protocolhubzugliftinghost',
            name='protocolName',
            field=models.CharField(default='Factory Out-Going inspection report', max_length=255),
        ),
    ]
