# Generated by Django 5.2.4 on 2025-12-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_rename_check_size_10_2_protocolhubzugliftinghost_check_size_1_21_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocollaufhubzug',
            name='isPermanentDone',
            field=models.BooleanField(default=True),
        ),
    ]
