# Generated by Django 5.2.4 on 2025-12-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_alter_protocollaufhubzug_ispermanentdone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocollaufhubzug',
            name='protocolName',
            field=models.CharField(default='Einstellprotokoll tems BMW Leipzig A5E53621916A', max_length=255),
        ),
    ]
