# Generated by Django 5.2.4 on 2026-05-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_protocolhubzugliftinghost_oknok_1_29_lp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolhubzuglaufseiltrommel',
            name='protocolName',
            field=models.CharField(default='Seperate parts list for each carrier', max_length=255),
        ),
        migrations.AlterField(
            model_name='protocolhubzugliftinghost',
            name='oknok_1_4_soll',
            field=models.TextField(blank=True, default='461', null=True),
        ),
        migrations.AlterField(
            model_name='protocolhubzugmassseiltrommel',
            name='protocolName',
            field=models.CharField(default='Checklist  TILT EMS - LAM Inspection Dimensions Assembly', max_length=255),
        ),
    ]
